<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AgenciaEnvio;

class AgenciaEnvioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Limpiar la tabla antes de sembrar
        AgenciaEnvio::query()->delete();

        $agencias = [
            // ========== AMAZONAS ==========
            ['nombre' => 'Chachapoyas Co Dos De Mayo', 'ciudad' => 'Chachapoyas', 'departamento' => 'Amazonas', 'direccion' => 'Jr. Dos De Mayo Cdra. 15 S/n Chachapoyas', 'referencia' => 'Junto A Terminal De Combis Etsa', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Chachapoyas Jr Grau', 'ciudad' => 'Chachapoyas', 'departamento' => 'Amazonas', 'direccion' => 'Jr. Grau 270', 'referencia' => 'Junto A La Agencia De Viajes Monteverde', 'tipo' => 'Pequeña'],
            ['nombre' => 'Bagua Capital', 'ciudad' => 'Bagua', 'departamento' => 'Amazonas', 'direccion' => 'Av. Héroes De Cenepa N° 345, Bagua - Bagua - Amazonas', 'referencia' => 'Frente Al', 'tipo' => 'Pequeña'],
            ['nombre' => 'Pedro Ruiz', 'ciudad' => 'Pedro Ruiz', 'departamento' => 'Amazonas', 'direccion' => 'Av. Sacsahuaman N° 513 - Pedro Ruiz', 'referencia' => 'A Media Cuadra De La Ugel', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Luya', 'ciudad' => 'Luya', 'departamento' => 'Amazonas', 'direccion' => 'Jr. Ramón Castilla S/n, Luya - Amazonas', 'referencia' => 'Entre El Colegio Secundario Ramón Castilla Y El Jr. José Gálvez, A Media Cdra. Del Agente De Venta De Pasajes De Civa, Móvil Y Transporte Chiclayo', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Bagua Grande', 'ciudad' => 'Bagua Grande', 'departamento' => 'Amazonas', 'direccion' => 'Av. Chachapoyas 1094 Sector Gonchillo', 'referencia' => 'A 2 Cuadras De La Clínica Señor De Los Milagros', 'tipo' => 'Grande / Co'],

            // ========== ANCASH ==========
            ['nombre' => 'Huaraz', 'ciudad' => 'Huaraz', 'departamento' => 'Ancash', 'direccion' => 'Av. 27 De Noviembre Cdra. 20 S/n - Villon Bajo', 'referencia' => 'Al Costado Del Grifo Primax', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Carhuaz', 'ciudad' => 'Carhuaz', 'departamento' => 'Ancash', 'direccion' => 'Carretera Central 00s/n Cent Carhuaz - Carhuaz - Áncash', 'referencia' => 'Media Cuadra Antes De Llegar Al Estadio Municipal Capitan Carlos Mejia', 'tipo' => 'Pequeña'],
            ['nombre' => 'Casma', 'ciudad' => 'Casma', 'departamento' => 'Ancash', 'direccion' => 'Av. Miguel Grau Mz. D 4 Lt. 1 Casma - Ancash', 'referencia' => 'Frente Al Jardín De Infancia', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Huarmey', 'ciudad' => 'Huarmey', 'departamento' => 'Ancash', 'direccion' => 'Carr. Panamericana Norte N° Km 293 Sect. Panamericana Huarmey – Ancash', 'referencia' => 'a 4 Cdras. Del Terminal Terrestre De Sur A Norte', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Caraz', 'ciudad' => 'Caraz', 'departamento' => 'Ancash', 'direccion' => 'Av. 9 De Octubre N° 259 - Huaylas', 'referencia' => 'Al Costado De La Empresa Móvil Tours', 'tipo' => 'Mediana'],
            ['nombre' => 'Chimbote Av Enrique Meiggs', 'ciudad' => 'Chimbote', 'departamento' => 'Ancash', 'direccion' => 'Av. Enrique Meiggs N° 2457', 'referencia' => '', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chimbote Av Jose Galvez', 'ciudad' => 'Chimbote', 'departamento' => 'Ancash', 'direccion' => 'Av. José Gálvez 791, Chimbote - Santa - Ancash', 'referencia' => 'a 1 Cdra. Antes De Llegar Al Puente Gálvez', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chimbote Av. Los Pescadores Co', 'ciudad' => 'Chimbote', 'departamento' => 'Ancash', 'direccion' => 'Par. Parcela N° 16757 - E Sector La Perla Tres Cabezas - Ancash', 'referencia' => 'frente Al Estadio Centenario', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chimbote Santa', 'ciudad' => 'Chimbote', 'departamento' => 'Ancash', 'direccion' => 'Panamericana Norte Km 442 - B, Santa', 'referencia' => 'Al Lado De La Ferreteria La Llave', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chimbote Ovalo De La Familia', 'ciudad' => 'Chimbote', 'departamento' => 'Ancash', 'direccion' => 'Urbanización José Carlos Mariategui (ex Unicreto) Mz R 3 Lt 3', 'referencia' => 'A Una Cuadra Del Óvalo La Familia', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chimbote Tres De Octubre', 'ciudad' => 'Chimbote', 'departamento' => 'Ancash', 'direccion' => 'Av. José Pardo Mz. K, Lt. 17 - Tres De Octubre', 'referencia' => 'Frente Al Óvalo Las Américas', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chimbote Garatea', 'ciudad' => 'Chimbote', 'departamento' => 'Ancash', 'direccion' => 'Urb. Nicolas Garatea Mz. 100 lt. 24 - Nuevo Chimbote - Santa - Ancash', 'referencia' => 'Frente Al Paradero Autos N.- Garatea', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chimbote Av. Pacífico Belen', 'ciudad' => 'Chimbote', 'departamento' => 'Ancash', 'direccion' => 'Aa.hh. Belen Mz O Lt 28 - Nuevo Chimbote - Santa - Ancash', 'referencia' => 'Frente Al Grifo Doxa', 'tipo' => 'Pequeña'],
            ['nombre' => 'Yungay', 'ciudad' => 'Yungay', 'departamento' => 'Ancash', 'direccion' => 'Jr. Industrial, Lte. 14 - Yungay', 'referencia' => 'Al Costado Del Terminal Terrestre Y La Tapiceria Fredy', 'tipo' => 'Mediana'],

            // ========== APURÍMAC ==========
            ['nombre' => 'Abancay', 'ciudad' => 'Abancay', 'departamento' => 'Apurímac', 'direccion' => 'Av. Panamericana S/n - Abancay - Apurímac', 'referencia' => 'A 100 Metros De La Comisaría De Bellavista, Al Costado De Maderera Vega', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Andahuaylas', 'ciudad' => 'Andahuaylas', 'departamento' => 'Apurímac', 'direccion' => 'Av. Los Cedros 274', 'referencia' => 'A 70 Metros Del Puente Del Hospital De Andahuaylas', 'tipo' => 'Grande / Co'],

            // ========== AREQUIPA ==========
            ['nombre' => 'Arequipa Av Parra 379 Co', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Av. Parra 379 - Arequipa', 'referencia' => '', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Arequipa Av Lima', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Av. Lima N° 406 – Alto Selva Alegre - Arequipa', 'referencia' => 'Esquina Con Av. Obrera Cuadra 20', 'tipo' => 'Pequeña'],
            ['nombre' => 'Arequipa Av Augusto Salazar Bondy', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Augusto Salazar Bondy Mz J Lt 4 Alto Selva Alegre - Arequipa', 'referencia' => 'a Media Cdra. De La Iglesia Guadalupe', 'tipo' => 'Pequeña'],
            ['nombre' => 'Arequipa Plaza La Tomilla', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Av. Ramón Castilla N° 1000 - B La Tomilla Cayma', 'referencia' => 'En La Misma Plaza Tomilla', 'tipo' => 'Pequeña'],
            ['nombre' => 'Arequipa Av Charcani', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Av. Charcani 401 Asoc. Jose Olaya', 'referencia' => 'Frente Al Colegio Mendel', 'tipo' => 'Pequeña'],
            ['nombre' => 'Arequipa Ciudad Municipal', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Mz. A, Sub Lt. 2 A, Asentamiento Poblacional Asociación Centro Industrial Las Canteras, Cerro Colorado - Arequipa', 'referencia' => 'Al Costado Del Grifo Primax', 'tipo' => 'Pequeña'],
            ['nombre' => 'Arequipa Asoc Las Flores - Av 54', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Asoc. Las Flores Zn.2 Mz.j Lt.8 - Cerro Colorado', 'referencia' => 'Av 54 - A Media Cuadra De Ferretería Gino', 'tipo' => 'Pequeña'],
            ['nombre' => 'Arequipa Av Pumacahua', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Urb. San Felipe Av Pumacahua Lt 14, Cerro Colorado Arequipa', 'referencia' => 'A Dos Cdras. Antes De Llegar Al Metro Cencosud / Ex Notaria Concha Revilla', 'tipo' => 'Mediana'],
            ['nombre' => 'Arequipa Zamacola', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Calle Yavarí 507 B - Zamacola - Cerro Colorado – Arequipa', 'referencia' => 'A Una Cuadra De La Posta De Zamacola (marcisa Campos)', 'tipo' => 'Pequeña'],
            ['nombre' => 'Arequipa Av Los Incas', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Av. Los Incas N° 604 Semirural Pachacutec – Cerro Colorado - Arequipa', 'referencia' => 'Esquina Con Calle San Martin Semirural Pachacutec', 'tipo' => 'Pequeña'],
            ['nombre' => 'Arequipa Autopista La Joya', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Asoc. Urbanizadora Peruarbo Sector Peru Zona I Mz. B4 Lt. 4 - Autopista La Joya - Arequipa', 'referencia' => 'Autopista Arequipa - La Joya, A Dos Cdras. Del Sauna Candamo', 'tipo' => 'Mediana'],
            ['nombre' => 'Arequipa Asoc. Nuevo Horizonte - Av. 54', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Nuevo Horizonte Mz.h Lote 12 - Cerro Colorado - Arequipa', 'referencia' => 'Con Av.54 A Cuatro Cdras. De Inkafarma', 'tipo' => 'Pequeña'],
            ['nombre' => 'Arequipa Jacobo Hunter', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Calle Argentina # 405 - A, Jacobo Hunter - Arequipa', 'referencia' => 'Frente Al Cajero De Caja Arequipa Y Esquina Con El Banco Caja Arequipa', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Arequipa El Cruce La Joya', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Lateral 12 C Lt. 32, El Cruce La Joya - Arequipa', 'referencia' => 'Al Costado Del Grifo Primax De La Joya', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Arequipa Mariano Melgar', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Calle Ancash N° 202 - Mariano Melgar', 'referencia' => 'A La Altura Del Coliseo Del Niño', 'tipo' => 'Pequeña'],
            ['nombre' => 'Arequipa Miraflores', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Av. Goyoneche N° 1422', 'referencia' => 'Esquina Francisco Bolognesi', 'tipo' => 'Micro'],
            ['nombre' => 'Arequipa Urb Manuel Prado', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Calle Belén N°100 - A Urb. Manuel Prado - Paucarpata', 'referencia' => 'A Espaldas Del Cc. Mall Aventura Porongoche', 'tipo' => 'Mini-micro'],
            ['nombre' => 'Arequipa Av Jesus', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Av. Jesús N° 1100 Paucarpata – Arequipa', 'referencia' => 'Con Esquina arturo Villegas N° 101', 'tipo' => 'Micro'],
            ['nombre' => 'Arequipa Av Socabaya - Los Toritos', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Av. Socabaya 301 - Urb. San Martín De Socabaya', 'referencia' => 'Al Frente Del Parque Victor Barriga', 'tipo' => 'Mini-micro'],
            ['nombre' => 'Arequipa Av. Horacio Zevallos', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Asentamiento Urbano Municipal Horacio Zeballos Gamez Sector E Mz. 1 Lt. 18 socabaya - Arequipa', 'referencia' => 'al Costado Del Colegio Joule Y/o 2 Cdras. Del Penal De Socabaya', 'tipo' => 'Mediana'],
            ['nombre' => 'Arequipa Uchumayo', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Urb. El Carmen M. E. Lt. 1 Congata Del Distrito Uchumayo - Arequipa', 'referencia' => 'A Dos Cdras. De La Comisaria Congata', 'tipo' => 'Pequeña'],
            ['nombre' => 'Arequipa Yura', 'ciudad' => 'Arequipa', 'departamento' => 'Arequipa', 'direccion' => 'Mz. O Lt. 4 Zna 2 Ciudad De Dios - Yura - Arequipa', 'referencia' => 'Carretera Yura', 'tipo' => 'Pequeña'],
            ['nombre' => 'Camaná', 'ciudad' => 'Camaná', 'departamento' => 'Arequipa', 'direccion' => 'Calle Agustín Gamarra N° 451, Cercado Camaná', 'referencia' => 'Al Frente Del Delivey Caseritos', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chala', 'ciudad' => 'Chala', 'departamento' => 'Arequipa', 'direccion' => 'Av. Emancipacion Lt. 3 Mz. 51, Chala - Caraveli - Arequipa', 'referencia' => 'A Media Cdra. De La Caja Arequipa', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Majes Pedregal', 'ciudad' => 'Majes', 'departamento' => 'Arequipa', 'direccion' => 'Lt. 4 De La Parcela 180, Vía Principal', 'referencia' => 'Frente Al Grifo El Eje', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Mollendo Co', 'ciudad' => 'Mollendo', 'departamento' => 'Arequipa', 'direccion' => 'Mariscal Castilla 472 –a, Arequipa - Islay - Mollendo', 'referencia' => 'al Costado De Cei "mi carrusel"', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Mollendo Cercado', 'ciudad' => 'Mollendo', 'departamento' => 'Arequipa', 'direccion' => 'Calle Dean Valdivia 388 Cercado', 'referencia' => 'Esquina Con Blondel', 'tipo' => 'Mini-micro'],
            ['nombre' => 'Cocachacra', 'ciudad' => 'Cocachacra', 'departamento' => 'Arequipa', 'direccion' => 'Centro Poblado Cocachacra Mz. N5 Sub-lote 5b Calle Dean Valdivia, Cocachacra - Islay - Arequipa', 'referencia' => 'del Parque San Francisco Una Cdra. Hacia Abajo', 'tipo' => 'Terminal'],
            ['nombre' => 'Matarani', 'ciudad' => 'Matarani', 'departamento' => 'Arequipa', 'direccion' => 'Asentamiento Humano. Puerto Nuevo Mz. I Lt. 18 Av. Bello Horizonte, islay - islay - Arequipa', 'referencia' => 'Frente Al Parque Ecológico', 'tipo' => 'Terminal'],

            // ========== AYACUCHO ==========
            ['nombre' => 'Ayacucho Co', 'ciudad' => 'Ayacucho', 'departamento' => 'Ayacucho', 'direccion' => 'Aa.hh Complejo Artesanal T1 Lt1 - Ayacucho', 'referencia' => 'A Una Cuadra De La Puerta 2 Del Terminal Terrestre Libertadores De América', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Ayacucho Carmen Alto', 'ciudad' => 'Ayacucho', 'departamento' => 'Ayacucho', 'direccion' => 'Asentamiento Humano Carmen Alto Mz B1 Lote 9 Zona Ii Acuchimay Carmen Alto – Huamanga- Ayacucho', 'referencia' => 'A 1 Cuadra De La Municipalidad De Carmen Alto', 'tipo' => 'Pequeña'],
            ['nombre' => 'Ayacucho Jesús Nazareno', 'ciudad' => 'Ayacucho', 'departamento' => 'Ayacucho', 'direccion' => 'Jr. José María Eguren 451 - Jesus Nazareno - Huamanga - Ayacucho', 'referencia' => 'Cruce Con Jr. Mariano Melgar', 'tipo' => 'Pequeña'],
            ['nombre' => 'Huanta', 'ciudad' => 'Huanta', 'departamento' => 'Ayacucho', 'direccion' => 'Jr. Gervasio Santillana N°976 - Huanta - Ayacucho', 'referencia' => 'Cruce Con Jr. Revolución', 'tipo' => 'Mediana'],

            // ========== CAJAMARCA ==========
            ['nombre' => 'Cajamarca Co', 'ciudad' => 'Cajamarca', 'departamento' => 'Cajamarca', 'direccion' => 'Av. Independencia N° 787 Barrio Santa Elena', 'referencia' => '', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Cajamarca Horacio Zevallos', 'ciudad' => 'Cajamarca', 'departamento' => 'Cajamarca', 'direccion' => 'Jr. Emilio Barrantes Mz X Lote 3 Urb. Horacio Zevallos - Cajamarca', 'referencia' => 'A Una Cuadra De La Universidad Privada Del Norte (upn) Y Vía De Evitamiento Norte Cuadra 13', 'tipo' => 'Mediana'],
            ['nombre' => 'Cajamarca Barrio San Jose', 'ciudad' => 'Cajamarca', 'departamento' => 'Cajamarca', 'direccion' => 'Jr. Chanchamayo N° 1162 - Barrio San José Cajamarca', 'referencia' => 'Paralela Con Jr. Huancavelica Y Jr. Sara Macdougall', 'tipo' => 'Mediana'],
            ['nombre' => 'Cajamarca Huambocancha Baja', 'ciudad' => 'Cajamarca', 'departamento' => 'Cajamarca', 'direccion' => 'Mz. A Lote S/n – Barrio Huambocancha Baja – Cajamarca', 'referencia' => 'A Una Cdra. Del Paradero De La P13/al Costado Del Campo Deportivo El Patriarca', 'tipo' => 'Pequeña'],
            ['nombre' => 'Cajamarca Huaraclla', 'ciudad' => 'Cajamarca', 'departamento' => 'Cajamarca', 'direccion' => 'Mz. A Lote S/n Cp Huaraclla - Jesus - Cajamarca', 'referencia' => 'A Una Cdra. De La I.e. José Olaya Balandra', 'tipo' => 'Mediana'],
            ['nombre' => 'Cajamarca Baños Del Inca', 'ciudad' => 'Cajamarca', 'departamento' => 'Cajamarca', 'direccion' => 'Jr. Cahuide N° 242 – Lotiz. Hurtado Miller – Baños Del Inca – Cajamarca', 'referencia' => 'A Espaldas De Senati Y A Una Cdra. De La Base De Serenazgo De Baños Del Inca', 'tipo' => 'Mediana'],
            ['nombre' => 'Cajabamba', 'ciudad' => 'Cajabamba', 'departamento' => 'Cajamarca', 'direccion' => 'Jr. Caceres N° 211 Cajabamba – Cajamarca', 'referencia' => 'Esquina Con Jose Leal', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Celendín', 'ciudad' => 'Celendín', 'departamento' => 'Cajamarca', 'direccion' => 'Jr. Pedro Ortiz Montoya 148', 'referencia' => 'Esquina Con Av. Amazonas', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Chota', 'ciudad' => 'Chota', 'departamento' => 'Cajamarca', 'direccion' => 'Av. Fray José Arana N 805', 'referencia' => 'Frente Al Terminal Angel Divino', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Chilete', 'ciudad' => 'Chilete', 'departamento' => 'Cajamarca', 'direccion' => 'Jr. Santa Rosa N° 130 - Chilete', 'referencia' => 'A 100 Del Puente De Ingreso A Chilete', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Tembladera Cajamarca', 'ciudad' => 'Tembladera', 'departamento' => 'Cajamarca', 'direccion' => 'Jr. Bolognesi S/n – Tembladera - Yonan - Contumazá - Cajamarca', 'referencia' => 'Al Frente Del Parque Víctor Raúl Haya De La Torre', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Cutervo', 'ciudad' => 'Cutervo', 'departamento' => 'Cajamarca', 'direccion' => 'Av. Salomón Vilchez Murga S/n. Cdra 9', 'referencia' => 'Frente A La Clínica Cutervo', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Bambamarca', 'ciudad' => 'Bambamarca', 'departamento' => 'Cajamarca', 'direccion' => 'Av. Tupac Amaru 1105', 'referencia' => 'Al Costado Del Paradero Al Cumbe', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Jaén', 'ciudad' => 'Jaén', 'departamento' => 'Cajamarca', 'direccion' => 'Av. Pakammuros Cuadra 6 S/n', 'referencia' => 'Esquina Con Calle Libertad N° 490', 'tipo' => 'Grande / Co'],
            ['nombre' => 'San Ignacio', 'ciudad' => 'San Ignacio', 'departamento' => 'Cajamarca', 'direccion' => 'Pasaje Tres N° 113 Urb Santa Rosa, Cajamarca - San Ignacio', 'referencia' => 'Frente Al Estado Municipal', 'tipo' => 'Grande / Co'],
            ['nombre' => 'San Marcos', 'ciudad' => 'San Marcos', 'departamento' => 'Cajamarca', 'direccion' => 'Jr. Adolfo Amorin Bueno N° 140 San Marcos – Cajamarca', 'referencia' => 'Al Frente De La Plaza Agropecuaria', 'tipo' => 'Grande / Co'],
            ['nombre' => 'San Miguel Cajamarca', 'ciudad' => 'San Miguel', 'departamento' => 'Cajamarca', 'direccion' => 'Jr. Bolognesi N° 717 – San Miguel – Cajamarca - Cajamarca', 'referencia' => 'Al Costado Del Coliseo Y El Paradero De Llapa Y Cochán', 'tipo' => 'Mediana'],
            ['nombre' => 'San Pablo Cajamarca', 'ciudad' => 'San Pablo', 'departamento' => 'Cajamarca', 'direccion' => 'Jr. Tnt. Lorenzo Iglesia N° 910 - San Pablo – Cajamarca - Cajamarca', 'referencia' => 'A Media Cdra. Del Hospital San Pablo', 'tipo' => 'Mediana'],

            // ========== CALLAO ==========
            ['nombre' => 'Callao Faucett', 'ciudad' => 'Callao', 'departamento' => 'Callao', 'direccion' => 'Av. Elmer Faucett N° 492', 'referencia' => '', 'tipo' => 'Mediana'],
            ['nombre' => 'Callao Av. Canta Callao', 'ciudad' => 'Callao', 'departamento' => 'Callao', 'direccion' => 'Av. Canta Callao 10 - Parcela 2a Local 109', 'referencia' => 'Al Frente De Tottus', 'tipo' => 'Pequeña'],
            ['nombre' => 'Callao Av Quilca', 'ciudad' => 'Callao', 'departamento' => 'Callao', 'direccion' => 'Unidad Inmobiliaria N° 1, Av. Quilca Mz. G Sub Lt. 11c, Urb. Aeropuerto – Segundo Sector - Callao', 'referencia' => 'Cruce Con Calle 1, Frente A La Iglesia De Testigos De Jehová', 'tipo' => 'Micro'],
            ['nombre' => 'Callao Av Bertello', 'ciudad' => 'Callao', 'departamento' => 'Callao', 'direccion' => 'Av. Alejandro Bertello Bollati mz. B Lt. 20 Y 21 – Urb. Progresiva Bahía Blanca – Callao - Callao - Callao', 'referencia' => 'Frente Al Mercado Costa Azul', 'tipo' => 'Pequeña'],
            ['nombre' => 'Callao Av Saenz Peña', 'ciudad' => 'Callao', 'departamento' => 'Callao', 'direccion' => 'Av. Saenz Peña N° 414 - 416 - Callao - Callao', 'referencia' => 'Cruce Con Av. Marco Polo', 'tipo' => 'Pequeña'],
            ['nombre' => 'Callao Bellavista', 'ciudad' => 'Callao', 'departamento' => 'Callao', 'direccion' => 'Av. Elmer Faucett 1641 - Urb. Jardines Virú Mz. B Lt 46, Bellavista - Callao', 'referencia' => 'A 2 Cuadras Del Cruce De Av. Faucett Con Av. Venezuela', 'tipo' => 'Pequeña'],
            ['nombre' => 'Callao Ovalo La Perla', 'ciudad' => 'Callao', 'departamento' => 'Callao', 'direccion' => 'Av. La Marina 530, Urb. Benjamin Doigg Lossio, La Perla, Callao', 'referencia' => 'a 3 Cuadras Del Óvalo De La Perla', 'tipo' => 'Micro'],
            ['nombre' => 'Ventanilla', 'ciudad' => 'Ventanilla', 'departamento' => 'Callao', 'direccion' => 'Calle 19, Mz. J Lt. 26 Zn - Urb. Coop. De La Marina', 'referencia' => 'Al Costado De Lubricentro Pablito Romero', 'tipo' => 'Pequeña'],
            ['nombre' => 'Pachacútec', 'ciudad' => 'Pachacútec', 'departamento' => 'Callao', 'direccion' => 'Urb. Popular De Interés Social (upis) – Proyecto Especial Ciudad Pachacutec, Mz. A, Lt. 23, Sect. G Pachacutec - Ventanilla', 'referencia' => 'Grifo Repsol Cruce De Av. 225 Con Av. Los Arquitectos', 'tipo' => 'Pequeña'],
            ['nombre' => 'Mi Peru', 'ciudad' => 'Mi Perú', 'departamento' => 'Callao', 'direccion' => 'V. Victor Raul Haya De La Torre Mz. A Lt. 02 Asentamiento Humano Confraternidad - Iii Sector - Mi peru – Callao - Callao', 'referencia' => 'Cruce Con Av. Arequipa', 'tipo' => 'Terminal'],

            // ========== CUSCO ==========
            ['nombre' => 'Cusco Tica Tica', 'ciudad' => 'Cusco', 'departamento' => 'Cusco', 'direccion' => 'Arco Ticatica Pustipata, Lt. N° A - 11 - 2, Cusco', 'referencia' => 'En La Av. Principal A 3 Cdras. Del Mercado Tica Tica', 'tipo' => 'Pequeña'],
            ['nombre' => 'Cusco San Jeronimo', 'ciudad' => 'Cusco', 'departamento' => 'Cusco', 'direccion' => 'Calle Ciro Alegría 226 - 224', 'referencia' => 'Una Cuadra Antes Del Paradero Penal En El Carril De Bajada', 'tipo' => 'Pequeña'],
            ['nombre' => 'Cusco Cachimayo - San Sebastian', 'ciudad' => 'Cusco', 'departamento' => 'Cusco', 'direccion' => 'Urb. Cachimayo A-37 Av. La Cultura – San Sebastian – Cusco', 'referencia' => 'Entre Paradero Enaco Y Parque Cachimayo, A 2 Cuadra De La Universidad Andina', 'tipo' => 'Pequeña'],
            ['nombre' => 'Cusco Via Expresa Sur', 'ciudad' => 'Cusco', 'departamento' => 'Cusco', 'direccion' => 'Urb. Tupac Amaru B-1-2 san Sebastian – Cusco', 'referencia' => 'Terminando La Via Expresa Zona Sur', 'tipo' => 'Micro'],
            ['nombre' => 'Cusco Av Antonio Lorena', 'ciudad' => 'Cusco', 'departamento' => 'Cusco', 'direccion' => 'Prolongación Av. Antonio Lorena # 140 - Santiago, Cusco', 'referencia' => 'Al Frente Del Cementerio Almudena', 'tipo' => 'Pequeña'],
            ['nombre' => 'Cusco Urb. Bancopata Av. Industrial', 'ciudad' => 'Cusco', 'departamento' => 'Cusco', 'direccion' => 'Av. Industrial Urb. Bancopata J-20, Santiago - Cusco', 'referencia' => 'a 2 Cdras. Del Ovalo Pachacutec, Frente A La Empresa Coca Cola', 'tipo' => 'Micro'],
            ['nombre' => 'Cusco Huancaro', 'ciudad' => 'Cusco', 'departamento' => 'Cusco', 'direccion' => 'Urb. Villa Union F-1-b Huancaro, Santiago - Cusco - Cusco', 'referencia' => 'Frente A La Iglesia De Los Mormones/ A Una Cdra. Del Mercado Huancaro', 'tipo' => 'Terminal'],
            ['nombre' => 'Cusco Co Parque Industrial', 'ciudad' => 'Cusco', 'departamento' => 'Cusco', 'direccion' => 'Av. Las Americas Mz. E Lt. 20, 2da Etapa, Urb. Parque Industrial, Wanchaq - Cusco', 'referencia' => 'Al Frente De Talleres Pfuro, Al Frente De Mederera Urpi, Paralela a La Av Via Expresa', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Cusco Av Pachacutec', 'ciudad' => 'Cusco', 'departamento' => 'Cusco', 'direccion' => 'Av. Pachacutec 429 - Wanchaq', 'referencia' => 'A 100 Mtrs. De La Piscina Wanchaq', 'tipo' => 'Pequeña'],
            ['nombre' => 'Cusco Velasco Astete', 'ciudad' => 'Cusco', 'departamento' => 'Cusco', 'direccion' => 'Velasco Astete D3 - Wanchaq', 'referencia' => 'A 2 Cdras. Del Aereopuerto', 'tipo' => 'Pequeña'],
            ['nombre' => 'Anta Izcuchaca', 'ciudad' => 'Anta', 'departamento' => 'Cusco', 'direccion' => 'Parque Del Carmen Lt. 1 Mz. B 2, Anta - Anta - Cusco', 'referencia' => 'Paradero Carmen, Pista Principal Izcuchaca', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Cusco Calca', 'ciudad' => 'Calca', 'departamento' => 'Cusco', 'direccion' => 'Av. Vilcanota Mz. A Lt 4 Calca - Cusco', 'referencia' => 'Frente Al Grifo Petro Perú O El Óvalo Puma - Entrada De Calca', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Pisac', 'ciudad' => 'Pisac', 'departamento' => 'Cusco', 'direccion' => 'Av Vilcanota S/n, Pisac - Calca - Cusco', 'referencia' => 'A Media Cdra. Del Puente De Pisac / Carretera A Taray', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Sicuani Co Ovalo San Andres', 'ciudad' => 'Sicuani', 'departamento' => 'Cusco', 'direccion' => 'Prolong. Av. Arequipa 1010 S/n', 'referencia' => 'Al Costado Del Grifo Guadalupe En El Óvalo San Andrés', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Sicuani Av Manuel Callo', 'ciudad' => 'Sicuani', 'departamento' => 'Cusco', 'direccion' => 'Jr. Inambari Nro. 208, Sicuani - Canchis - Cusco', 'referencia' => 'Al Frente Del Bcp Y De Caja Piura', 'tipo' => 'Pequeña'],
            ['nombre' => 'Combapata', 'ciudad' => 'Combapata', 'departamento' => 'Cusco', 'direccion' => 'Av. Señor De Huanca S/n - Combapata - Canchis - Cusco', 'referencia' => 'Al Costado Del Grifo Señor De Qoylluriti - A Orillas De La Misma Carretera A Sicuani', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Santo Tomas', 'ciudad' => 'Santo Tomas', 'departamento' => 'Cusco', 'direccion' => 'Calle Bolognesi Mz. 02 Lt. 25, Santo Tomas - Chumbivilcas - Cusco', 'referencia' => 'A Espaldas De La Polleria Pico Dorado Y A Media Cdra. De La Av Santa Barbara', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Espinar', 'ciudad' => 'Espinar', 'departamento' => 'Cusco', 'direccion' => 'Av. Tintaya N° 215 Espinar', 'referencia' => 'A Dos Cuadra S De Los Bomberos', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Quillabamba', 'ciudad' => 'Quillabamba', 'departamento' => 'Cusco', 'direccion' => 'Jr. Puno Lt. 10 Y 11 Mz. G Urb. Santa Ana, Cusco - La Convencion - Santa Ana', 'referencia' => 'A Media Cdra.l Del Estadio Municipal De Quillabamba / Cruce Con Prolongacion Jr. Martin Pio Concha', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Urcos', 'ciudad' => 'Urcos', 'departamento' => 'Cusco', 'direccion' => 'Mayupata S/n Paucarbamba, Urcos - Quispicanchi - Cusco', 'referencia' => 'Al Frende Del Estadio Municipal De Urcos / Al Frente Del Terminal Terrestre De Urcos', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Oropesa', 'ciudad' => 'Oropesa', 'departamento' => 'Cusco', 'direccion' => 'Sec. Chimpapampa Apv. Jose Ccarlos Mareategui s/n, Oropesa - Quispicanchi - Cusco', 'referencia' => 'A Una Cdra. De La Carreta A Urcos / A Una Cdra. De La Panificadora Cachito Amarillo', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Cusco Urubamba', 'ciudad' => 'Urubamba', 'departamento' => 'Cusco', 'direccion' => 'Asoc. Pro Vivienda Vilcanota - Cusco', 'referencia' => 'Frente Al Hotel San Agustin', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Chinchero', 'ciudad' => 'Chinchero', 'departamento' => 'Cusco', 'direccion' => 'Av. Mateo Pumacahua S/n, Chinchero - Urubamba - Cusco', 'referencia' => 'Al costado De La Caja Cusco / En La Misma Carretera A Urubamba', 'tipo' => 'Grande / Co'],

            // ========== HUANCAVELICA ==========
            ['nombre' => 'Huancavelica', 'ciudad' => 'Huancavelica', 'departamento' => 'Huancavelica', 'direccion' => 'Av. Universitaria 1003 - Huancavelica', 'referencia' => 'A 1 Cdra. De La Escuela Santa Ana Y A 3 Cdras. Del Puente Del Ejército (barrio Santa Ana)', 'tipo' => 'Grande / Co'],

            // ========== HUÁNUCO ==========
            ['nombre' => 'Huánuco Jr Aguilar', 'ciudad' => 'Huánuco', 'departamento' => 'Huánuco', 'direccion' => 'Jr. Aguilar N° 872 - Huánuco', 'referencia' => '', 'tipo' => 'Pequeña'],
            ['nombre' => 'Huánuco Amarilis Co', 'ciudad' => 'Huánuco', 'departamento' => 'Huánuco', 'direccion' => 'Jr. Los Pinos Lote 3 -d2 Urb Los Pinos - Amarilis - Huánuco', 'referencia' => 'A La Espalda De Toyota Huánuco', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Ambo', 'ciudad' => 'Ambo', 'departamento' => 'Huánuco', 'direccion' => 'Av. Las Americas 501', 'referencia' => 'Al Frente Del Colegio Juan José Crespo Y Castillo', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Tingo María Co Buenos Aires', 'ciudad' => 'Tingo María', 'departamento' => 'Huánuco', 'direccion' => 'Calle Rosario Central', 'referencia' => 'Segunda Entrada De Buenos Aires, En La Misma Esquina', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Tingo María - Amazonas', 'ciudad' => 'Tingo María', 'departamento' => 'Huánuco', 'direccion' => 'Av. Amazonas Nro 778 - Leoncio Prado', 'referencia' => 'A 1 Cuadra Del Reniec', 'tipo' => 'Mini-micro'],
            ['nombre' => 'Aucayacu', 'ciudad' => 'Aucayacu', 'departamento' => 'Huánuco', 'direccion' => 'Jr. Chiclayo 247 0c-02 Cent Aucayu, Leoncio Prado, Huánuco', 'referencia' => 'Atrás Del Estadio Municipal', 'tipo' => 'Grande / Co'],

            // ========== ICA ==========
            ['nombre' => 'Ica San Joaquin', 'ciudad' => 'Ica', 'departamento' => 'Ica', 'direccion' => 'Pasaje Grau N° 101 San Joaquin - Ica', 'referencia' => 'A 1 Cdra De Petro Peru', 'tipo' => 'Micro'],
            ['nombre' => 'Ica Av. Jj Elias', 'ciudad' => 'Ica', 'departamento' => 'Ica', 'direccion' => 'Manzana B, Sub-lote 02 Del Fundo La Palma Ica', 'referencia' => 'Cruce De Av. Cutervo Con Av. J.j Elias', 'tipo' => 'Micro'],
            ['nombre' => 'Ica Urb. Manzanilla', 'ciudad' => 'Ica', 'departamento' => 'Ica', 'direccion' => 'Av. Manuel Santana Chiri N°359 A1 – Ica', 'referencia' => 'Cruce Con Calle Baltazar Caravedo', 'tipo' => 'Micro'],
            ['nombre' => 'Ica La Tinguiña', 'ciudad' => 'Ica', 'departamento' => 'Ica', 'direccion' => 'Av. Victorio Gotuzzo N° 506 - Tinguiña - Ica', 'referencia' => 'Cruce Con Fray Ramón Rosas, Al Costado De La Comisaria P.n.p. La Tinguiña', 'tipo' => 'Micro'],
            ['nombre' => 'Ica Parcona', 'ciudad' => 'Ica', 'departamento' => 'Ica', 'direccion' => 'Cp. De Parcona -cercado (primera Etapa) Mz. B Lote 16 Parcona - Ica', 'referencia' => 'Av. 18 De Febrero y Cruce De Av. Natividad Paco', 'tipo' => 'Pequeña'],
            ['nombre' => 'Ica Salas', 'ciudad' => 'Ica', 'departamento' => 'Ica', 'direccion' => 'Sub Lote 01 zona panamericana sur km. 293.350, Salas guadalupe - Ica - Ica', 'referencia' => 'Frente Al Estadio De Salas Guadalupe', 'tipo' => 'Pequeña'],
            ['nombre' => 'Ica Santiago', 'ciudad' => 'Ica', 'departamento' => 'Ica', 'direccion' => 'Centro Poblado Santiago Mz. E, Lt. 01 Sector Ii Santiago - Ica - Ica', 'referencia' => 'Frente A La Comisaria De Santiago', 'tipo' => 'Pequeña'],
            ['nombre' => 'Ica Subtanjalla Co', 'ciudad' => 'Ica', 'departamento' => 'Ica', 'direccion' => 'C.p - Sector Macacona /predio Parcela 214 Lote 2, Subtanjalla - Ica - Ica', 'referencia' => 'Panamericana Sur Frente A La Entrada Del Arrabal', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Chincha Prolong Luis Massaro', 'ciudad' => 'Chincha', 'departamento' => 'Ica', 'direccion' => 'Prolongacion Luis Massaro N°247 - Chincha Alta', 'referencia' => '', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chincha Calle Los Angeles', 'ciudad' => 'Chincha', 'departamento' => 'Ica', 'direccion' => 'Calle Los Ángeles N° Casa 217 01 - A Sin Barriio Cercado, Chincha Alta - Chincha - Ica', 'referencia' => 'A 2 Cdras. De La Plaza De Armas De Chncha Pasando Electrodunas', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chincha Pueblo Nuevo', 'ciudad' => 'Chincha', 'departamento' => 'Ica', 'direccion' => 'Aa. Hh. Los Alamos, Calle Los Laureles Mz. 17 Lt. 11- A', 'referencia' => 'A 2 Cdras. De La Posta Los Álamos', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chincha Sunampe Co', 'ciudad' => 'Chincha', 'departamento' => 'Ica', 'direccion' => 'Carr. Panamericana sur Nro. 198 -b , Sin Barrio Cercado Sunampe, Sunampe - Chincha - Ica', 'referencia' => 'Antigua panamericana Sur Frente A La Entrada De Grocio Prado', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Nasca', 'ciudad' => 'Nasca', 'departamento' => 'Ica', 'direccion' => 'En La Esquina De La Av. Circunvalación Con Calle S/n, Hoy Calle Las Mercedes S/n Nasca', 'referencia' => 'Al Lado De La Iep Jean Piaget', 'tipo' => 'Grande / Co'],
            ['nombre' => 'El Ingenio', 'ciudad' => 'El Ingenio', 'departamento' => 'Ica', 'direccion' => 'Av. Principal Tulin 204, El Ingenio - Nazca - Ica', 'referencia' => 'Fremte A A La Plaza De Tulin', 'tipo' => 'Mediana'],
            ['nombre' => 'San Juan De Marcona', 'ciudad' => 'San Juan De Marcona', 'departamento' => 'Ica', 'direccion' => 'Aa.hh. San Martín De Porres E-4 San Juan De Marcona - Nazca - Ica', 'referencia' => 'cruce De Av. Las Orquídeas Con Av. San Martin De Porras A Dos Puertas Del Hotel San Martin', 'tipo' => 'Mediana'],
            ['nombre' => 'Pisco Av Abraham Valdelomar Co', 'ciudad' => 'Pisco', 'departamento' => 'Ica', 'direccion' => 'Av. Abraham Valdelomar S/n, Urb. Residencial Paracas Mz C Lt 14 - Pisco', 'referencia' => 'Cruce Con Av. Las Américas, Al Costado De La Posta San Martin', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Pisco La Villa Cruce', 'ciudad' => 'Pisco', 'departamento' => 'Ica', 'direccion' => 'C. P. Oblacion Villa Los Angeles Mz.a Lt 13 B La Villa pisco-pisco-ica', 'referencia' => 'A 100 Metros Con Dirección Al Sur Dedl Cruce Panamericana Antigua C/n Av. Fermín Tangüis', 'tipo' => 'Pequeña'],
            ['nombre' => 'Pisco San Clemente', 'ciudad' => 'Pisco', 'departamento' => 'Ica', 'direccion' => 'Av. Los Libertadores Grupo Número 1 Mz,91 Lote 7ª San Clemente - Pisco - Ica', 'referencia' => 'Libertadores Sexta Cuadra,frente Del Grifo Santa Rosa', 'tipo' => 'Pequeña'],

            // ========== JUNÍN ==========
            ['nombre' => 'Huancayo Jr. Ica', 'ciudad' => 'Huancayo', 'departamento' => 'Junín', 'direccion' => 'Jr. Ica Nº 1143 - Huancayo', 'referencia' => 'Entre El Jr. Ica Y El Jr. Tacna', 'tipo' => 'Pequeña'],
            ['nombre' => 'Huancayo Terminal De Bus', 'ciudad' => 'Huancayo', 'departamento' => 'Junín', 'direccion' => 'Av. Evitamiento S/n - Counter N°13', 'referencia' => '', 'tipo' => 'Terminal'],
            ['nombre' => 'Huancayo Terminal Los Andes', 'ciudad' => 'Huancayo', 'departamento' => 'Junín', 'direccion' => 'Av. Ferrocarril S/n - Huancayo - Counter N° 14', 'referencia' => 'Terminal Terrestre Los Andes, Frente Al Open Plaza', 'tipo' => 'Micro'],
            ['nombre' => 'Huancayo San Carlos', 'ciudad' => 'Huancayo', 'departamento' => 'Junín', 'direccion' => 'Pj. San Fernando 209 Huancayo - Huancayo - Junin', 'referencia' => 'Esquina Del Jr. San Fernando Y Mártires Del Periodismo', 'tipo' => 'Pequeña'],
            ['nombre' => 'Huancayo Chilca', 'ciudad' => 'Huancayo', 'departamento' => 'Junín', 'direccion' => 'Jr. 28 De Julio N° 935', 'referencia' => 'Esquina 28 De Julio Y Santos Chocano', 'tipo' => 'Pequeña'],
            ['nombre' => 'Huancayo Av Mariscal Castilla Co Parque Industrial', 'ciudad' => 'Huancayo', 'departamento' => 'Junín', 'direccion' => 'Av Mariscal Castilla 2769', 'referencia' => 'Frente Al Colegio Andres Bello', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Huancayo Pio Pata', 'ciudad' => 'Huancayo', 'departamento' => 'Junín', 'direccion' => 'Av. Huancavelica 1201, El Tambo - Huancayo - Junín', 'referencia' => 'Esquina Con El Jr. La Victoria', 'tipo' => 'Pequeña'],
            ['nombre' => 'Huancayo Av Circunvalación Cruce Con Mariategui', 'ciudad' => 'Huancayo', 'departamento' => 'Junín', 'direccion' => 'Av. Circunvalación 480 T-1, El Tambo - Huancayo - Junin', 'referencia' => 'Esquina Con Prolongación Mariategui', 'tipo' => 'Pequeña'],
            ['nombre' => 'Huancayo Ciudad Universitaria', 'ciudad' => 'Huancayo', 'departamento' => 'Junín', 'direccion' => 'Jr Tarma Nro. 37 - 24, El Tambo - Huancayo - Junín', 'referencia' => 'Al Costado De La Facultad De Ingeniería Metalúrgica Uncp', 'tipo' => 'Micro'],
            ['nombre' => 'Huancayo Pilcomayo', 'ciudad' => 'Huancayo', 'departamento' => 'Junín', 'direccion' => 'Plaza Independencia 131, Pilcomayo - Huancayo - Junín', 'referencia' => 'Plaza Principal De Pilcomayo', 'tipo' => 'Pequeña'],
            ['nombre' => 'Huancayo San Agustin De Cajas', 'ciudad' => 'Huancayo', 'departamento' => 'Junín', 'direccion' => 'Carretera Central Km 7.5 S/n San Agustin – Huancayo – Junín', 'referencia' => 'Frente A La Envasadora Solgas', 'tipo' => 'Pequeña'],
            ['nombre' => 'Concepción', 'ciudad' => 'Concepción', 'departamento' => 'Junín', 'direccion' => 'Carretera Central Lt. 7 - Mz. E5, Concepción - Concepción - Junín', 'referencia' => 'Esquina Con Tupac Amaru', 'tipo' => 'Pequeña'],
            ['nombre' => 'La Merced', 'ciudad' => 'La Merced', 'departamento' => 'Junín', 'direccion' => 'Av. Peru 931 Sector Pampa Del Carmen, La Merced -chanchamayo - Junín', 'referencia' => 'Frente A La Cooperativa Chanchamayo', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Perené', 'ciudad' => 'Perené', 'departamento' => 'Junín', 'direccion' => 'Av. Marginal S/n Aa.vv San Jacinto - perene - Chanchamayo - Junin', 'referencia' => 'Antes Del Ultimo Rompemuelle De San Jacinto', 'tipo' => 'Mediana'],
            ['nombre' => 'Pichanaki', 'ciudad' => 'Pichanaki', 'departamento' => 'Junín', 'direccion' => 'Av. Venus Lt. 20 Ciudad Satélite', 'referencia' => 'A 1 Cuadra Y Media Del Parque De Satélite', 'tipo' => 'Grande / Co'],
            ['nombre' => 'San Ramón', 'ciudad' => 'San Ramón', 'departamento' => 'Junín', 'direccion' => 'Jr. Ucayali 102 - San Ramón', 'referencia' => 'Frente A La Caja Huancayo Y El Parque El Avión', 'tipo' => 'Pequeña'],
            ['nombre' => 'Jauja', 'ciudad' => 'Jauja', 'departamento' => 'Junín', 'direccion' => 'Jr. Estanislao Marquez 286, Yauyos - Jauja - Junín', 'referencia' => 'Esquina Con Jr. 4 De Enero', 'tipo' => 'Mediana'],
            ['nombre' => 'Satipo', 'ciudad' => 'Satipo', 'departamento' => 'Junín', 'direccion' => 'Jr. Francisco Irazola 1077 - Junín', 'referencia' => 'Fábrica La Satipeña', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Mazamari', 'ciudad' => 'Mazamari', 'departamento' => 'Junín', 'direccion' => 'Jr. Jorge Chavez Nro 144 Lt. 8a Junín - Satipo– Mazamari', 'referencia' => 'Cerca A La Vía Principal, Al Costado Del Hospedaje Luján 1er Piso', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Pangoa', 'ciudad' => 'Pangoa', 'departamento' => 'Junín', 'direccion' => 'Av. Marginal S/n Número Villa Chavini Pangoa - Satipo - Junín', 'referencia' => 'Al Costado De La Tienda Honda Inversiones Arauco San Martín De Pangoa', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Tarma', 'ciudad' => 'Tarma', 'departamento' => 'Junín', 'direccion' => 'Jr. Amazonas Nro. 1164 Tarma - Junín', 'referencia' => 'entre Jr. Amazonas Con Av. Vienrich', 'tipo' => 'Grande / Co'],
            ['nombre' => 'La Oroya', 'ciudad' => 'La Oroya', 'departamento' => 'Junín', 'direccion' => 'Av. Arévalo S/n (carretera Central) - Anexo El Tambo - Santa Rosa De Sacco', 'referencia' => '', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Chupaca', 'ciudad' => 'Chupaca', 'departamento' => 'Junín', 'direccion' => 'Jr. Ramon Castilla 201, Chupaca - Chupaca - Junin', 'referencia' => 'A Una Cdra. De La Plaza Principal De Chupaca', 'tipo' => 'Pequeña'],

            // ========== LA LIBERTAD ==========
            ['nombre' => 'Trujillo Calle Liverpool', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Calle Liverpool N° 329 / Urb. Santa Isabel - Trujillo', 'referencia' => 'A Una Cuadra Antes De La Iglesia De Mansiche', 'tipo' => 'Mediana'],
            ['nombre' => 'Trujillo America Sur', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Av. América Sur 1736 - Trujillo', 'referencia' => 'Frente Al Estadio Chan Chan', 'tipo' => 'Micro'],
            ['nombre' => 'Trujillo La Perla', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Av. La Perla Mz. E Lote 05 Urb. Ingenieria – Trujillo – La Libertad', 'referencia' => 'A 1 Cdra. Del Colegio Bruning', 'tipo' => 'Pequeña'],
            ['nombre' => 'Trujillo Atahualpa', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Calle Atahualpa 481 – Trujillo – La Libertad', 'referencia' => 'A 1/2 Cdra De La Av Los Incas', 'tipo' => 'Pequeña'],
            ['nombre' => 'Trujillo Aeropuerto', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Aeropuerto Internacional Capitán Fap Carlos Martinez De Pinillos', 'referencia' => '', 'tipo' => 'Terminal'],
            ['nombre' => 'Trujillo Calle Santa Cruz - America Sur', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Calle Santa Cruz n° 389 Chicago - Trujillo - La Libertad', 'referencia' => 'A Media Cdra. De La Av. America Sur/a Media Cuadra Del Estadio Chan Chan', 'tipo' => 'Mediana'],
            ['nombre' => 'Trujillo Av Hnos Uceda - America Norte', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Av. Hermanos Uceda Meza N° 269 Urb Miraflores Ii Etapa - trujillo - Trujillo - La Libertad', 'referencia' => 'A Una Cdra. De Av. America Norte. / Entre Av. Miraflores Y Av. Salvador Lara', 'tipo' => 'Pequeña'],
            ['nombre' => 'Trujillo Ovalo Papal', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Urb. Vista Hermosa Mz. F Lt. 11 Piso °1 Trujillo - Trujillo - La Libertad', 'referencia' => 'A Espaldas Del Metro Del Ovalo Papal', 'tipo' => 'Pequeña'],
            ['nombre' => 'Trujillo Av Hermanos Angulo', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Av. Hermanos Angulo 628, Trujillo', 'referencia' => 'A Espaldas De La Municipalidad El Porvenir', 'tipo' => 'Mini-micro'],
            ['nombre' => 'Trujillo Alto Trujillo', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Av. Prolongación 12 De Noviembre, Mz. Q, Lt. 25', 'referencia' => 'A Media Cdra. De La Comisaría Alto Trujillo', 'tipo' => 'Pequeña'],
            ['nombre' => 'Trujillo Av. Las Magnolias', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Av. Las Magnolias Mz. 25 Lt. 2a Nuevo Porvenir, El Porvenir - Trujillo - La Libertad', 'referencia' => 'A Una Cdra. Del Poder Judicial Cisaj Sede El Porvenir', 'tipo' => 'Pequeña'],
            ['nombre' => 'Trujillo Jr. Cahuide', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Jr. Cahuide N° 342 Aa.hh La Merced - El Porvenir - Trujillo - La Libertad', 'referencia' => 'A Una Cdra. Del Arco Del Porvenir / A Una Cdra. De La Parroquia El Buen Pastor', 'tipo' => 'Pequeña'],
            ['nombre' => 'Trujillo Ovalo Huanchaco Co', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Carretera Via De Evitamiento 576.2 Huanchaquito Alto - Trujillo - La Libertad', 'referencia' => 'A 1 Cdra. De Ovalo Huanchaco / Al Costado De Condominio Las Brisas', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Trujillo El Milagro', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Av. Industrial Mz 23 Lt. 13 Sector Ii – el Milagro, Huanchaco - Trujillo - La Libertad', 'referencia' => 'A 2 cdras. de la plaza de armas de el Milagro', 'tipo' => 'Pequeña'],
            ['nombre' => 'Trujillo Av Tahuantinsuyo', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Av. Tahuantinsuyo N° 739, la Esperanza – trujillo – la Libertad', 'referencia' => 'Diagonal A Grifo El Amigo. / Entre Pasaje Santa Ana Y Av. Los Laureles', 'tipo' => 'Pequeña'],
            ['nombre' => 'Trujillo Wichanzao', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Mz. 1 Lt. 23 Aa.hh Wichanzao – la Esperanza – trujillo – la Libertad', 'referencia' => 'Al Costado Del Almacén Sunat. / Diagonal Al Hospital De Alta Complejidad Virgen De La Puerta', 'tipo' => 'Pequeña'],
            ['nombre' => 'Trujillo Moche', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Av. La Marina Lote 25 - B – Moche – Trujillo - La Libertad', 'referencia' => 'A Media Cdra De La Comisaría De Moche', 'tipo' => 'Pequeña'],
            ['nombre' => 'Trujillo Av Larco', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Av. Larco 865, Trujillo - Trujillo - La Libertad', 'referencia' => 'Mz X Lt 28 Cui San Andres V Etapa Tercer Sector Y Frente Al Colegio Jesus Maria', 'tipo' => 'Pequeña'],
            ['nombre' => 'Trujillo Paijan', 'ciudad' => 'Trujillo', 'departamento' => 'La Libertad', 'direccion' => 'Av. Panamericana Norte N° 1320 - Paijan', 'referencia' => '', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Casa Grande', 'ciudad' => 'Casa Grande', 'departamento' => 'La Libertad', 'direccion' => 'Calle Luis sánchez N° 152 Sector Parte Alta. Casa Grande - Ascope - La Libertad', 'referencia' => 'Cruce Con av. Estadio', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chepén', 'ciudad' => 'Chepén', 'departamento' => 'La Libertad', 'direccion' => 'Prolongacion Ezequiel Gonzales Caceda 193 - Sec. Chepen', 'referencia' => 'Frente Al Coliseo', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Pacanguilla', 'ciudad' => 'Pacanguilla', 'departamento' => 'La Libertad', 'direccion' => 'Carretera Panamericana # 835 - Urb. Pacanguilla - Distrito Pacanga', 'referencia' => 'En La Misma Panamericana', 'tipo' => 'Mediana'],
            ['nombre' => 'Otuzco', 'ciudad' => 'Otuzco', 'departamento' => 'La Libertad', 'direccion' => 'Av. Alfredo Gutiérrez N° 120 - Otuzco - Otuzco - La Libertad', 'referencia' => '', 'tipo' => 'Grande / Co'],
            ['nombre' => 'San Pedro De Lloc', 'ciudad' => 'San Pedro De Lloc', 'departamento' => 'La Libertad', 'direccion' => 'Av. Vía De Evitamiento N° 407, San Pedro De Lloc - Pacasmayo - La Libertad', 'referencia' => 'A Media Cdra. De La Calle Libertad/ A Media Cdra. Del Paradero De La Via De Evitamiento', 'tipo' => 'Pequeña'],
            ['nombre' => 'Ciudad De Dios', 'ciudad' => 'Ciudad De Dios', 'departamento' => 'La Libertad', 'direccion' => 'Mz. A Lt. 01 Cpm Ciudad De Dios - Sec. Los Ángeles – Guadalupe – La Libertad', 'referencia' => 'Al Costado Del Molino Samán Y A Dos Cuadras Del Cruce A Cajamarca', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Guadalupe La Libertad', 'ciudad' => 'Guadalupe', 'departamento' => 'La Libertad', 'direccion' => 'Av. Nilla Cerruty N° 299 - Guadalupe – Pacasmayo – La Libertad', 'referencia' => 'Al Costado Del Grifo Repsol - Neotech', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Pacasmayo Las Palmeras', 'ciudad' => 'Pacasmayo', 'departamento' => 'La Libertad', 'direccion' => 'Ctra. Panamericana Norte N° Mz. P Lt. 4a - A.h. Las Palmeras', 'referencia' => 'Entre Av. Sucre Y Av. Leoncio Prado', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Pacasmayo Centro', 'ciudad' => 'Pacasmayo', 'departamento' => 'La Libertad', 'direccion' => 'Av. Gonzalo Ugaz Salcedo S/n - Pacasmayo - La Libertad', 'referencia' => 'Al Costado Del Estadio Municipal De Pacasmayo / A Media Cdra. Del Supermercado Tottus', 'tipo' => 'Mini-micro'],
            ['nombre' => 'Huamachuco', 'ciudad' => 'Huamachuco', 'departamento' => 'La Libertad', 'direccion' => 'Jr. Simon Bolivar 763, Huamachuco Sanchez Carrion - La Libertad', 'referencia' => 'Entre Jr. Independecia Y Jr. Alfonso Ugarte', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Virú Puente Viru', 'ciudad' => 'Virú', 'departamento' => 'La Libertad', 'direccion' => 'Panamericana Norte N° 933 Puente Virú - Virú - La Libertad', 'referencia' => 'A Media Cdra. Del Grifo Zona Etna/media Cdra. Del Semaforo Zona Etna', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Virú Centro', 'ciudad' => 'Virú', 'departamento' => 'La Libertad', 'direccion' => 'Calle Puno N° 125 - Mz. 32 Lt. 7a - Virú - La Libertad', 'referencia' => 'A Media Cdra. Del Cruce De La Av. Viru Con La Calle Jorge Chavez / a Media Cdra. De La Plazuela Maria Parado De Bellido', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chao', 'ciudad' => 'Chao', 'departamento' => 'La Libertad', 'direccion' => 'Av. Victor Raul Haya De La Torre 575 Chao - Viru', 'referencia' => 'A Media Cdra. De La Comisaría De Chao', 'tipo' => 'Grande / Co'],

            // ========== LAMBAYEQUE ==========
            ['nombre' => 'Chiclayo Miraflores', 'ciudad' => 'Chiclayo', 'departamento' => 'Lambayeque', 'direccion' => 'Av. Panamericana 975 Pp Jj Luis Alberto Sanchez, Chiclayo - Chiclayo - Lambayeque', 'referencia' => 'A Media Cdra. Del Ovalo Señor De Sipan / Al Frente De Derco Center', 'tipo' => 'Mediana'],
            ['nombre' => 'Chiclayo Mariscal Nieto', 'ciudad' => 'Chiclayo', 'departamento' => 'Lambayeque', 'direccion' => 'Calle Mariscal Nieto N° 390', 'referencia' => 'Entre Mariscal Nieto Y Miguel Grau', 'tipo' => 'Micro'],
            ['nombre' => 'Chiclayo Av Las Americas', 'ciudad' => 'Chiclayo', 'departamento' => 'Lambayeque', 'direccion' => 'Av. Las Américas Lt. 42 Mz. D, Urb. Monterrico - I Etapa, Chiclayo - Chiclayo - Lambayeque', 'referencia' => 'A Media Cdra. entre La Av. Colectora Y Av. Las Americas Y A Media Cdra. Del Grifo Sr. De Sipán', 'tipo' => 'Mediana'],
            ['nombre' => 'Chiclayo Chongoyape', 'ciudad' => 'Chiclayo', 'departamento' => 'Lambayeque', 'direccion' => 'Av. Atahualpa N° 1200 - Chongoyape - Chiclayo - Lambayeque', 'referencia' => 'Interseccion Con Calle Iquitos / A 2 Cdras. De La Interseccion Con La Av. Chiclayo', 'tipo' => 'Terminal'],
            ['nombre' => 'Chiclayo Calle Tahuantinsuyo', 'ciudad' => 'Chiclayo', 'departamento' => 'Lambayeque', 'direccion' => 'Calle Tahuantinsuyo 995 - Urb. San Lorenzo - Jose Leonardo Ortiz - Chiclayo - Lambayeque', 'referencia' => 'Entre La Cdra. 2 De Av. América Y La Calle Tahuantinsuyo/a Media Cdra. De La Iglesia Los Mormones', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chiclayo Av Balta Cdra. 36', 'ciudad' => 'Chiclayo', 'departamento' => 'Lambayeque', 'direccion' => 'Av. Jose Balta N° 3653 C.p.m. Primero De Mayo Jose Leonardo Ortiz -chiclayo -lambayeque', 'referencia' => 'Entre La Av. Balta Y Néstor Barsallo / a 2 Cuadras De La Av. Chiclayo', 'tipo' => 'Mediana'],
            ['nombre' => 'Chiclayo Av Victor R. Haya Co', 'ciudad' => 'Chiclayo', 'departamento' => 'Lambayeque', 'direccion' => 'Av. Víctor Raul Haya De La Torre 2470 La Victoria - Chiclayo', 'referencia' => 'Entre La Via Evitamiento Y Panamericana', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Chiclayo Monsefu', 'ciudad' => 'Chiclayo', 'departamento' => 'Lambayeque', 'direccion' => 'av. Venezuela N° 221, Monsefú - Chiclayo - Lambayeque', 'referencia' => 'A Media Cdra. De La Calle Diego Ferre Y A Cdra. Y Media Del Parque Artesanal De Monsefú', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chiclayo Pimentel', 'ciudad' => 'Chiclayo', 'departamento' => 'Lambayeque', 'direccion' => 'Calle Miguel Grau Mz B Lote 3 - pimentel - chiclayo - Lambayeque', 'referencia' => 'Al Costado De La Comisaria De Pimentel', 'tipo' => 'Mediana'],
            ['nombre' => 'Chiclayo Reque', 'ciudad' => 'Chiclayo', 'departamento' => 'Lambayeque', 'direccion' => 'Av. Mariscal Ramon Castilla Mz. 4 Lote 14, Reque - Chiclayo - Lambayeque', 'referencia' => 'A Media Cdra. De La Interseccion Con Calle San Martin / A Unos Mtrs De Alborada Eventos Y Recepciones', 'tipo' => 'Terminal'],
            ['nombre' => 'Chiclayo Pomalca', 'ciudad' => 'Chiclayo', 'departamento' => 'Lambayeque', 'direccion' => 'Calle 25 Mz. I Lt. 6 Sect. 6 San Juan, Pomalca - Chiclayo - Lambayeque', 'referencia' => 'A Una Cdra. Y Media De La Intersección Con Av. San Martin/ Al Frente De La Iglesia Mormon', 'tipo' => 'Terminal'],
            ['nombre' => 'Chiclayo Tuman', 'ciudad' => 'Chiclayo', 'departamento' => 'Lambayeque', 'direccion' => 'Av. El Progreso N° 52 - Sector Santa Rosa', 'referencia' => 'Entre La Av. El Progreso Y 1° De Mayo, Frente A La Canchita De Grass Sintético', 'tipo' => 'Mediana'],
            ['nombre' => 'Ferreñafe', 'ciudad' => 'Ferreñafe', 'departamento' => 'Lambayeque', 'direccion' => 'Av. Andrés A. Cáceres N°550a', 'referencia' => 'Al Costado Del Grifo Primax', 'tipo' => 'Mediana'],
            ['nombre' => 'Lambayeque Panamericana', 'ciudad' => 'Lambayeque', 'departamento' => 'Lambayeque', 'direccion' => 'Calle Paraguay Mz. D Lt 2a Unidad Vecinal Indoamérica - lambayeque', 'referencia' => 'Al Costado De La Fábrica De Kinkones Bruning / A 01 Cuadra Del Puente Lambayeque', 'tipo' => 'Mediana'],
            ['nombre' => 'Lambayeque Centro', 'ciudad' => 'Lambayeque', 'departamento' => 'Lambayeque', 'direccion' => 'Av. Federico Villarreal N° 491, Lambayeque - Lambayeque - Lambayeque', 'referencia' => 'A Media Cdra. De La Interseccion De La av. Federico Villarreal Con Calle Emiliano Niño', 'tipo' => 'Micro'],
            ['nombre' => 'Jayanca', 'ciudad' => 'Jayanca', 'departamento' => 'Lambayeque', 'direccion' => 'Calle Diego Ferre N°1321 - jayanca - Lambayeque', 'referencia' => 'Al Frente Del Centro De Salud De Jayanca / A Media Cdra. Del Grifo Asia', 'tipo' => 'Mediana'],
            ['nombre' => 'Morrope', 'ciudad' => 'Morrope', 'departamento' => 'Lambayeque', 'direccion' => 'Calle Tahuantinsuyo N° 821, Morrope - Lambayeque', 'referencia' => 'Frente Al Parque Infantil De Morrope', 'tipo' => 'Mediana'],
            ['nombre' => 'Motupe', 'ciudad' => 'Motupe', 'departamento' => 'Lambayeque', 'direccion' => 'Calle Los Pinos N°116 - Lotizacion La Primavera', 'referencia' => 'A Media Cuadra De La Panamericana Carretera Fernando Belaunde Terry', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Olmos', 'ciudad' => 'Olmos', 'departamento' => 'Lambayeque', 'direccion' => 'Av. Augusto B. Leguía Mz. 87 Lt. 32  - olmos - Lambayeque', 'referencia' => 'Al Frente De La Comisaria De Olmos', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Tucume', 'ciudad' => 'Tucume', 'departamento' => 'Lambayeque', 'direccion' => 'Av. Federico Villarreal N° 982 (ctra. Fernando Belaunde Terry)', 'referencia' => 'A Media Cdra. Del Cementerio Jardines De La Paz', 'tipo' => 'Mediana'],

            // ========== LORETO ==========
            ['nombre' => 'Iquitos Jr Francisco Bolognesi', 'ciudad' => 'Iquitos', 'departamento' => 'Loreto', 'direccion' => 'Jr. Francisco Bolognesi Nro 203 - 215 Iquitos', 'referencia' => 'Esquina Con Putumayo', 'tipo' => 'Pequeña'],
            ['nombre' => 'Iquitos Puerto Iquitos Terminal', 'ciudad' => 'Iquitos', 'departamento' => 'Loreto', 'direccion' => 'Jr. Pablo Rossell 590 Con Nanay', 'referencia' => 'Cruce Con Av. Nanay Frente Al Instituto Cepro América Computer', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Iquitos Av Tupac Amaru', 'ciudad' => 'Iquitos', 'departamento' => 'Loreto', 'direccion' => 'Av. Tupac Amaru Con - Calle Lourdes De León #479 iquitos Maynas - Loreto', 'referencia' => 'Frente A La Botica Thiagofama', 'tipo' => 'Pequeña'],
            ['nombre' => 'Iquitos Punchana', 'ciudad' => 'Iquitos', 'departamento' => 'Loreto', 'direccion' => 'Calle Borja N°648 Punchana - Maynas - Loreto', 'referencia' => 'Al Costado De La Farmacia San Carlos Centro Médico', 'tipo' => 'Pequeña'],
            ['nombre' => 'Iquitos Av Participacion Parcela', 'ciudad' => 'Iquitos', 'departamento' => 'Loreto', 'direccion' => 'Av. Participación Parcela 9-a San Juan Bautista - Maynas - Loreto', 'referencia' => 'Frente Al Lavadero Osito Y A Media Cdra. Del Parque 1 De Enero', 'tipo' => 'Pequeña'],
            ['nombre' => 'Iquitos Av Jose A. Quiñones', 'ciudad' => 'Iquitos', 'departamento' => 'Loreto', 'direccion' => 'Av. José Abelardo Quiñones # 2475 San Juan Bautista - Maynas - Loreto', 'referencia' => 'Frente A La Universidad Científica Del Perú (ucp)', 'tipo' => 'Pequeña'],
            ['nombre' => 'Yurimaguas', 'ciudad' => 'Yurimaguas', 'departamento' => 'Loreto', 'direccion' => 'Calle Jorge Chávez N° 300', 'referencia' => 'Esquina Con Progreso, Al Costado De Enapu', 'tipo' => 'Pequeña'],
            ['nombre' => 'Yurimaguas Puerto', 'ciudad' => 'Yurimaguas', 'departamento' => 'Loreto', 'direccion' => 'Terminal', 'referencia' => '', 'tipo' => 'Grande / Co'],

            // ========== MADRE DE DIOS ==========
            ['nombre' => 'Tambopata Av La Joya Co', 'ciudad' => 'Puerto Maldonado', 'departamento' => 'Madre de Dios', 'direccion' => 'Av. La Joya N° 122 - Pto. Maldonado', 'referencia' => 'Frente Al Óvalo De Los Otorongos', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Tambopata Jr. Jaime Troncoso', 'ciudad' => 'Puerto Maldonado', 'departamento' => 'Madre de Dios', 'direccion' => 'Jr. Jaime Troncoso 442, Tambopata - Madre De Dios', 'referencia' => 'A Media Cdra. Del Jardin Piloto / A Media Cdra. De La Empresa Real Dorado', 'tipo' => 'Micro'],
            ['nombre' => 'Tambopata Av Circunvalacion', 'ciudad' => 'Puerto Maldonado', 'departamento' => 'Madre de Dios', 'direccion' => 'Av. Circunvalacion Mz. C Lt. 01, Tambopata - Tambopata - Madre De Dios', 'referencia' => 'A Dos Cdras. De La Carretera Interoceanica Sur / Cruce Con Jr. Las Mercedes Cabello', 'tipo' => 'Pequeña'],
            ['nombre' => 'Mazuko', 'ciudad' => 'Mazuko', 'departamento' => 'Madre de Dios', 'direccion' => 'Av. Inambari Fraccion N° 07, Inambari - Tambopata - Madre De Dios', 'referencia' => 'Al Frente Del Restaurante Carbon Rojo Mazuko', 'tipo' => 'Grande / Co'],
            ['nombre' => 'El Triunfo', 'ciudad' => 'El Triunfo', 'departamento' => 'Madre de Dios', 'direccion' => 'Av. Interoceanica Km. 1 , Las Piedras - Tambopata - Madre De Dios', 'referencia' => 'Al Costado Del Grifo Virgen Natividad', 'tipo' => 'Micro'],
            ['nombre' => 'Iberia', 'ciudad' => 'Iberia', 'departamento' => 'Madre de Dios', 'direccion' => 'Av. Jorge Chavez Mz. H1 Sub Lote 11-b, Iberia - Tahuamanu - Madre De Dios', 'referencia' => 'A Una Cdra. De La Empresa Real Dorado / A Una Cdra. Y Media De La Av Jose Aldamiz', 'tipo' => 'Grande / Co'],

            // ========== MOQUEGUA ==========
            ['nombre' => 'Moquegua San Antonio', 'ciudad' => 'Moquegua', 'departamento' => 'Moquegua', 'direccion' => 'Av. Santa Fortunata Mz. N5 Lt. 10 Asoc. Villa Moquegua San Antonio', 'referencia' => 'A Una Cuadra De La Casa De La Mujer', 'tipo' => 'Pequeña'],
            ['nombre' => 'Moquegua Calle Lima', 'ciudad' => 'Moquegua', 'departamento' => 'Moquegua', 'direccion' => 'Calle Lima 190 - Mariscal Nieto - Moquegua', 'referencia' => 'A Dos Cuadras Del Parque Los Héroes/alameda', 'tipo' => 'Micro'],
            ['nombre' => 'Moquegua Quebrada Las Lechuzas Co', 'ciudad' => 'Moquegua', 'departamento' => 'Moquegua', 'direccion' => 'Sector Quebrada Las Lechuzas Moquegua Calle N°1 Mz H Lt. 04, Moquegua - Mariscal Nieto - Moquegua', 'referencia' => 'Quebrada De Lechuzas', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Moquegua Chen Chen', 'ciudad' => 'Moquegua', 'departamento' => 'Moquegua', 'direccion' => 'Mz. C Lt. 24 – Asociación César Vizcarra – Centro Poblado Chen Chen , Moquegua –mariscal Nieto – Moquegua', 'referencia' => 'Al Costado Del Ovalo Chen Chen', 'tipo' => 'Pequeña'],
            ['nombre' => 'Ilo Co Pampa Inalambrica', 'ciudad' => 'Ilo', 'departamento' => 'Moquegua', 'direccion' => 'Urb. Ciudad Del Pescador, Mz. J Lt. 18-19', 'referencia' => 'A Dos Cuadras Del Poder Judicial', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Ilo Puerto', 'ciudad' => 'Ilo', 'departamento' => 'Moquegua', 'direccion' => 'Jr. Callao Prolongación Mz. N, Lt. 19 - A', 'referencia' => 'A Media Cdra. De La Cooperativa Cuajone', 'tipo' => 'Pequeña'],
            ['nombre' => 'Ilo Pacocha', 'ciudad' => 'Ilo', 'departamento' => 'Moquegua', 'direccion' => 'Agrupación De Familias Pueblo Nuevo M.z E2 Lt. Com2a Sect. Ii – Ilo - Moquegua', 'referencia' => 'Al Costado Del Banco Bcp', 'tipo' => 'Pequeña'],

            // ========== PASCO ==========
            ['nombre' => 'Cerro De Pasco', 'ciudad' => 'Cerro de Pasco', 'departamento' => 'Pasco', 'direccion' => 'Jr. Huaricapcha S/n A.h. Tupac Amaru Chaupimarca', 'referencia' => 'Frente Al Nuevo Terminal', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Huayllay', 'ciudad' => 'Huayllay', 'departamento' => 'Pasco', 'direccion' => 'Calle Lima S/n Barrio Arenales Huayllay Pasco', 'referencia' => 'Al Costado Del Colegio Cesar Vallejo', 'tipo' => 'Mediana'],
            ['nombre' => 'Oxapampa', 'ciudad' => 'Oxapampa', 'departamento' => 'Pasco', 'direccion' => 'Mz. 239 Sub Lote H – 1 Oxapampa - Oxapampa - Pasco', 'referencia' => 'Entre Av. Angélica Frey Y Jr. Lima', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Villa Rica', 'ciudad' => 'Villa Rica', 'departamento' => 'Pasco', 'direccion' => 'Av. Leopoldo Krausse N° 442 Villa Rica - Oxapampa - Pasco', 'referencia' => 'Entre El Jr. Pozuzo Y Jr. Cooperativa, Al Costado De La Notaría Guerra Y A 20 Metros De La Plaza Principal', 'tipo' => 'Grande / Co'],

            // ========== PIURA ==========
            ['nombre' => 'Piura Av. Luis Eguiguren', 'ciudad' => 'Piura', 'departamento' => 'Piura', 'direccion' => 'Av. Málaga Mz. A Lt.20 Int. 105 Piura', 'referencia' => 'A Media Cuadra De Honda Del Peru S.a. En El Cruce De Av. Luis Eguiguren Con Sullana Norte', 'tipo' => 'Pequeña'],
            ['nombre' => 'Piura Av. Grau', 'ciudad' => 'Piura', 'departamento' => 'Piura', 'direccion' => 'Av. Grau Manzana N, Lote 33 - Urbanización La Alborada', 'referencia' => 'Grau Con Marcavelica', 'tipo' => 'Mediana'],
            ['nombre' => 'Piura Av Raul Mata La Cruz- Dos Grifos', 'ciudad' => 'Piura', 'departamento' => 'Piura', 'direccion' => 'Av. Raúl Mata La Cruz Lt. 11 Mz. C Urb. Los Jardines - Corpiura, - Piura - Piura - Piura', 'referencia' => 'A Una Cdra. De Los 2 Grifos En Toda La Av. Raúl Mata La Cruz', 'tipo' => 'Mediana'],
            ['nombre' => 'Piura Av Tacna', 'ciudad' => 'Piura', 'departamento' => 'Piura', 'direccion' => 'Av. Tacna 509 Castilla - Piura', 'referencia' => 'Frente A Ugel De Castilla', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Piura Tacala', 'ciudad' => 'Piura', 'departamento' => 'Piura', 'direccion' => 'Aa.hh. San Valentín Mz. N Lt. 12 Castilla - Piura', 'referencia' => 'Al Costado Del Colegio Pedro Ruiz Gallo', 'tipo' => 'Mediana'],
            ['nombre' => 'Piura Catacaos', 'ciudad' => 'Piura', 'departamento' => 'Piura', 'direccion' => 'Av. Francisco Bolognesi Mz. 60 Lt. 37 Catacaos - Piura - Piura', 'referencia' => 'Al Lado Del Ex Pronei', 'tipo' => 'Mediana'],
            ['nombre' => 'Piura La Union', 'ciudad' => 'Piura', 'departamento' => 'Piura', 'direccion' => 'Av. Lima N° 590', 'referencia' => 'Frente A Tiendas Chancafe Q', 'tipo' => 'Mediana'],
            ['nombre' => 'Piura Las Lomas', 'ciudad' => 'Piura', 'departamento' => 'Piura', 'direccion' => 'Jr. Miguel Grau Mz. H Lt. 7, Las Lomas - Piura', 'referencia' => 'Al Costado De Caja Huancayo Y Al Costado De Comisaria Las Lomas', 'tipo' => 'Mediana'],
            ['nombre' => 'Piura Tambo Grande', 'ciudad' => 'Piura', 'departamento' => 'Piura', 'direccion' => 'Av. Arámbulo Santín N° 100, Mz. D Lt. E Aa. Hh. Andrés Rázuri', 'referencia' => 'A Dos Cuadras Del Estadio Deportivo', 'tipo' => 'Mediana'],
            ['nombre' => 'Piura Calle Emaús', 'ciudad' => 'Piura', 'departamento' => 'Piura', 'direccion' => 'Calle Tres N° 102, Sublote N° 1d Mz. Y - Zona Industrial Ii, Distrito 26 De Octubre', 'referencia' => 'Al Costado De Senati', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Piura Parque Industrial Co', 'ciudad' => 'Piura', 'departamento' => 'Piura', 'direccion' => 'Urb. Parque Industrial Piura Futura Mz. G, Lt. 1a. 26 De Octubre - Piura', 'referencia' => 'Al Frente Del Grifo Petro Perú', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Piura Av. Gullman', 'ciudad' => 'Piura', 'departamento' => 'Piura', 'direccion' => 'A.a.h.h. Consuelo De Velasco 1 Etapa Sector B Mz Lt.18 26 De Octubre – Piura', 'referencia' => 'Cruce Av. Circunvalación Con Av. Gullman Al Costado De La Ferreteria los Reyes', 'tipo' => 'Mediana'],
            ['nombre' => 'Piura Aahh Santa Rosa', 'ciudad' => 'Piura', 'departamento' => 'Piura', 'direccion' => 'Urb. Santa Rosa Mz. D Lt. 7, Sect. 7, 26 De Octubre - Piura', 'referencia' => 'Av. Raul Mata La Cruz Con Circunvalación Al Frente De Repuestos Frank|', 'tipo' => 'Pequeña'],
            ['nombre' => 'Ayabaca', 'ciudad' => 'Ayabaca', 'departamento' => 'Piura', 'direccion' => 'Calle Bolognesi N° 136', 'referencia' => 'A 2 Cuadras De La Plaza De Armas De Ayabaca', 'tipo' => 'Mediana'],
            ['nombre' => 'Paimas', 'ciudad' => 'Paimas', 'departamento' => 'Piura', 'direccion' => 'Av. Sullana S/n', 'referencia' => 'Frente Al Complejo Educativo Juan Velasco Alvarado', 'tipo' => 'Pequeña'],
            ['nombre' => 'Huancabamba', 'ciudad' => 'Huancabamba', 'departamento' => 'Piura', 'direccion' => 'Av. Ramon Castilla 0351 Huancabamba - Piura', 'referencia' => 'A 1 Cuadra De La Capilla Ramon Castilla', 'tipo' => 'Mediana'],
            ['nombre' => 'Chulucanas', 'ciudad' => 'Chulucanas', 'departamento' => 'Piura', 'direccion' => 'Jr. Huancavelica N° 548', 'referencia' => 'Al Lado Del Terminal De Ronco', 'tipo' => 'Mediana'],
            ['nombre' => 'Morropón', 'ciudad' => 'Morropón', 'departamento' => 'Piura', 'direccion' => 'Jr. Adrianzén N° 099, Morropon - Morropon - Piura', 'referencia' => 'A Espaldas De Del Terminal Terrestre De Trampsa', 'tipo' => 'Mediana'],
            ['nombre' => 'Paita', 'ciudad' => 'Paita', 'departamento' => 'Piura', 'direccion' => 'Mz. H Lt. 14 Urb. Sol Y Mar - Paita', 'referencia' => 'Al Costado De La Empresa San Miguel', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Sullana Santa Rosa', 'ciudad' => 'Sullana', 'departamento' => 'Piura', 'direccion' => 'Carretera Panamericana Norte Nº 790 Sullana', 'referencia' => 'Frente Al Colegio Chiquititos', 'tipo' => 'Pequeña'],
            ['nombre' => 'Sullana Co Zona Industrial', 'ciudad' => 'Sullana', 'departamento' => 'Piura', 'direccion' => 'Ctra. Sullana Nº S/n Mz. K, Lt. 06 - Zona Industrial Municipal', 'referencia' => 'Al Costado Del Hotel Coco Suite', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Sullana Bellavista', 'ciudad' => 'Sullana', 'departamento' => 'Piura', 'direccion' => 'Calle Moquegua 381, Bellavista', 'referencia' => 'Rest. Parrilladas Chavelos', 'tipo' => 'Pequeña'],
            ['nombre' => 'Sullana Ignacio Escudero', 'ciudad' => 'Sullana', 'departamento' => 'Piura', 'direccion' => 'Av. Panamericana Calle 26 Lote 3, Ignacio Escudero - Sullana - Piura', 'referencia' => 'Frente A La Institución Educativa Ignacio Escudero', 'tipo' => 'Mediana'],
            ['nombre' => 'Talara Co Asoc California', 'ciudad' => 'Talara', 'departamento' => 'Piura', 'direccion' => 'Asociación California C - 03 Frente A Carretera Negritos, Talara - Pariñas', 'referencia' => 'Al Costado Del Restaurante Mi Torete', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Talara Alta 9 De Octubre', 'ciudad' => 'Talara', 'departamento' => 'Piura', 'direccion' => 'Mz. N-10 Aa.hh 9 De Octubre talara Alta, pariñas - Talara - Piura', 'referencia' => 'A 1 Cdra. Antes De Amecfa', 'tipo' => 'Pequeña'],
            ['nombre' => 'Talara Baja Parque 22', 'ciudad' => 'Talara', 'departamento' => 'Piura', 'direccion' => 'Parque 22 – 03 Lateral. Talara Baja, Pariñas - Talara - Piura', 'referencia' => 'Frente A Minsa', 'tipo' => 'Pequeña'],
            ['nombre' => 'El Alto', 'ciudad' => 'El Alto', 'departamento' => 'Piura', 'direccion' => 'Av. Bolognesi O-37 Centro El Alto', 'referencia' => 'A Espaldas De La Municipalidad De El Alto', 'tipo' => 'Mediana'],
            ['nombre' => 'Los Organos', 'ciudad' => 'Los Órganos', 'departamento' => 'Piura', 'direccion' => 'Av. Panamericana Norte P-29 - Urb. Cercado Zona Urbana', 'referencia' => 'Al Frente De Grifo De Troncos O Grifo San Pedro', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Máncora', 'ciudad' => 'Máncora', 'departamento' => 'Piura', 'direccion' => 'Av. Grau Nro. 432 Máncora - Talara - Piura', 'referencia' => 'Frente Al Paradero De Autos De Los Órganos En Toda La Panamericana Norte', 'tipo' => 'Mediana'],
            ['nombre' => 'Sechura', 'ciudad' => 'Sechura', 'departamento' => 'Piura', 'direccion' => 'Av. Bayovar N° 311', 'referencia' => 'Al Costado De Antena 10 Radio', 'tipo' => 'Mediana'],

            // ========== PUNO (SOLO DESAGUADERO) ==========
            ['nombre' => 'Desaguadero', 'ciudad' => 'Desaguadero', 'departamento' => 'Puno', 'direccion' => 'Av. 28 De Julio N° 564 - 566, Chucuito', 'referencia' => 'A 50 Mtrs. Del Banco De La Nacion', 'tipo' => 'Grande / Co'],

            // ========== SAN MARTÍN ==========
            ['nombre' => 'Moyobamba Centro', 'ciudad' => 'Moyobamba', 'departamento' => 'San Martín', 'direccion' => 'Jr. Serafín Filomeno N°279, Moyobamba - Moyobamba - San Martín', 'referencia' => 'A Una Cuadra Imedia Del Cumo (centro Cultural De Moyobamba)', 'tipo' => 'Pequeña'],
            ['nombre' => 'Moyobamba Soritor', 'ciudad' => 'Moyobamba', 'departamento' => 'San Martín', 'direccion' => 'Jr. Miguel Grau Cdra 7 N°741 Mz.05 Lte.16b, Soritor - Moyobamba - San Martín', 'referencia' => 'A Media Cdra. De La Iglesia Asambleas De Dios', 'tipo' => 'Mediana'],
            ['nombre' => 'San Martin Bellavista', 'ciudad' => 'Bellavista', 'departamento' => 'San Martín', 'direccion' => 'Av. Lima S/n Cdra. 8 - Bellavista', 'referencia' => 'Al Costado De La Polleria La Cabaña O Al Poder Judicial', 'tipo' => 'Grande / Co'],
            ['nombre' => 'San Jose De Sisa', 'ciudad' => 'San José de Sisa', 'departamento' => 'San Martín', 'direccion' => 'Jr. Bolognesi Cdra 6, San Jose De Sisa - El Dorado - San Martin', 'referencia' => 'Altura De Jr Lamas Y Jr Eladio Tapullima', 'tipo' => 'Mediana'],
            ['nombre' => 'Lamas', 'ciudad' => 'Lamas', 'departamento' => 'San Martín', 'direccion' => 'Jr. 16 De Octubre N°1137', 'referencia' => 'A La Espalda Del Grifo Vargas Tello', 'tipo' => 'Mediana'],
            ['nombre' => 'Juanjuí Fernando Belaunde Terry Co', 'ciudad' => 'Juanjuí', 'departamento' => 'San Martín', 'direccion' => 'Carretera Fernando Terry Km. 1 S/n', 'referencia' => 'Al Costado De Paradero De Autos Huallaga Express', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Juanjui Centro', 'ciudad' => 'Juanjuí', 'departamento' => 'San Martín', 'direccion' => 'Jr. Sargento Lorez N° 568, Juanjui - Mariscal Cáceres - San Martin', 'referencia' => 'A una Cdra. De Del Jr. Huallaga Cdra. 11 Y A Una Cdra. De Importaciones Patricia', 'tipo' => 'Pequeña'],
            ['nombre' => 'Picota', 'ciudad' => 'Picota', 'departamento' => 'San Martín', 'direccion' => 'Av. Fernando Belaunde Terry Lote 2b Picota - Picota - San Martin', 'referencia' => 'A Una Cdra. De La Comisaria De Picota Salida A Bellavista', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Rioja', 'ciudad' => 'Rioja', 'departamento' => 'San Martín', 'direccion' => 'Ctra. Fernando Belaúnde Terry N° 415', 'referencia' => 'Al Costado De La Clínica Chilcon Hope', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Nueva Cajamarca', 'ciudad' => 'Nueva Cajamarca', 'departamento' => 'San Martín', 'direccion' => 'Av. Cajamarca Norte Mz. 51 Lt. 15', 'referencia' => 'Al Costado De Essalud', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Tarapoto Co Jr Alfonso Ugarte', 'ciudad' => 'Tarapoto', 'departamento' => 'San Martín', 'direccion' => 'Jr. Alfonso Ugarte N°2283 - Tarapoto - San Martin - San Martin', 'referencia' => 'frente A La Cancha Sintético El Golazo', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Tarapoto Jr Leoncio Prado', 'ciudad' => 'Tarapoto', 'departamento' => 'San Martín', 'direccion' => 'Jr. Leoncio Prado N° 1175', 'referencia' => 'A Una Cuadra Del Instituto María Parado De Bellido', 'tipo' => 'Pequeña'],
            ['nombre' => 'Tarapoto Jr. Tahuantinsuyo', 'ciudad' => 'Tarapoto', 'departamento' => 'San Martín', 'direccion' => 'Jr. Tahuantinsuyo N° 158 - Tarapoto - San Martín', 'referencia' => 'Al Costado Del Grifo San Martín', 'tipo' => 'Pequeña'],
            ['nombre' => 'Tarapoto Jr. Ramón Castilla', 'ciudad' => 'Tarapoto', 'departamento' => 'San Martín', 'direccion' => 'Jr. Ramon Castilla N°1362 Tarapoto - San Martin', 'referencia' => 'A Media Cdra. De Mannucci Motor S.a', 'tipo' => 'Pequeña'],
            ['nombre' => 'Tarapoto La Banda De Shilcayo', 'ciudad' => 'Tarapoto', 'departamento' => 'San Martín', 'direccion' => 'Jr. Perú N°186', 'referencia' => 'A 2 Cdrs. De La Plaza De La Banda De Shilcayo', 'tipo' => 'Pequeña'],
            ['nombre' => 'Tarapoto Jr. Sargento Lorez', 'ciudad' => 'Tarapoto', 'departamento' => 'San Martín', 'direccion' => 'Jr. Sargento Lorez N° 264, Morales - San Martin', 'referencia' => 'A Una Cdra. Y Media De La Plaza De Morales, Frente A Vulcano Gas', 'tipo' => 'Pequeña'],
            ['nombre' => 'Tocache Av Fernando Belaunde', 'ciudad' => 'Tocache', 'departamento' => 'San Martín', 'direccion' => 'Av. Fernando Belaunde C-09 Mz H6 (21), Lt. 04, Cercado De Tocache', 'referencia' => 'Frente Al Mercadillo De Tocache', 'tipo' => 'Pequeña'],
            ['nombre' => 'Tocache Jr Fredy Aliaga Co', 'ciudad' => 'Tocache', 'departamento' => 'San Martín', 'direccion' => 'Jr. Fredy Aliaga N°3046 -tocache - Tocache - San Martin', 'referencia' => 'al Costado Del Recreo Campestre Estragos', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Uchiza', 'ciudad' => 'Uchiza', 'departamento' => 'San Martín', 'direccion' => 'Av. Leoncio Prado N°524 - Uchiza - Tocache - San Martin', 'referencia' => 'A Media Cdra. De La Plaza Central / Frente A Coopact', 'tipo' => 'Pequeña'],

            // ========== TACNA ==========
            ['nombre' => 'Tacna Co Av. Jorge Basadre', 'ciudad' => 'Tacna', 'departamento' => 'Tacna', 'direccion' => 'Av. Jorge Basadre Grohmann Oeste N° 366 - Tacna', 'referencia' => '', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Tacna Av Vigil', 'ciudad' => 'Tacna', 'departamento' => 'Tacna', 'direccion' => 'Av. Vigil 1636', 'referencia' => 'A Una Cdra. De La Plaza Grau', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Tacna Av. Arias Araguez', 'ciudad' => 'Tacna', 'departamento' => 'Tacna', 'direccion' => 'Calle Arias Araguez N° 836 tacna', 'referencia' => 'A Una Cdra. Antes De Llegar Al Coliseo Perú', 'tipo' => 'Pequeña'],
            ['nombre' => 'Tacna Av Ejercito', 'ciudad' => 'Tacna', 'departamento' => 'Tacna', 'direccion' => 'Av. Litoral Nro. 306 – Para Chico (anterior Av. Ejército Prolongación 306 Tacna), Tacna - Tacna - Tacna', 'referencia' => 'Dentro Del Establecimiento Del Grifo Primax', 'tipo' => 'Pequeña'],
            ['nombre' => 'Tacna Pocollay', 'ciudad' => 'Tacna', 'departamento' => 'Tacna', 'direccion' => 'Pueblo Tradicional Pocollay Mz. T Lote 01 , Pocollay - Tacna - Tacna', 'referencia' => 'A Una Cdra. Del Centro De Salud Pocollay', 'tipo' => 'Pequeña'],
            ['nombre' => 'Tacna Ciudad Nueva', 'ciudad' => 'Tacna', 'departamento' => 'Tacna', 'direccion' => 'Ciudad Nueva Mz 46 Lt 12 Comité 10 Ciudad Nueva - Tacna', 'referencia' => 'A Una Cdra. De La Plaza José Olaya De Ciudad Nueva', 'tipo' => 'Pequeña'],
            ['nombre' => 'Tacna Villa San Francisco', 'ciudad' => 'Tacna', 'departamento' => 'Tacna', 'direccion' => 'Asoc. Villa San Francisco Mz. 94 Lt. 22', 'referencia' => 'Cerca A Caja Cusco', 'tipo' => 'Pequeña'],
            ['nombre' => 'Tacna Av. Municipal', 'ciudad' => 'Tacna', 'departamento' => 'Tacna', 'direccion' => 'Asociación Las vilcas mz. E Lt. 16, Gregorio Albarracín Lanchipa - Tacna', 'referencia' => 'Frente Al Mercado Héroes Del Cenepa', 'tipo' => 'Pequeña'],

            // ========== TUMBES ==========
            ['nombre' => 'Tumbes - Av Arica', 'ciudad' => 'Tumbes', 'departamento' => 'Tumbes', 'direccion' => 'Av. Arica N° 227 - Tumbes', 'referencia' => '', 'tipo' => 'Pequeña'],
            ['nombre' => 'Tumbes Puyango', 'ciudad' => 'Tumbes', 'departamento' => 'Tumbes', 'direccion' => 'Urb. Andrés Araujo Morán Mz. 28-a Lote 03 Calle Jacinto Seminario', 'referencia' => 'Al Costado Del Mercado Puyango', 'tipo' => 'Pequeña'],
            ['nombre' => 'Tumbes Co - Panamericana Norte Km 2360', 'ciudad' => 'Tumbes', 'departamento' => 'Tumbes', 'direccion' => 'Av. Panamericana Norte S/n Villa Primavera - Tumbes', 'referencia' => 'Pasando Senati Frente A Agripac', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Tumbes Pampa Grande', 'ciudad' => 'Tumbes', 'departamento' => 'Tumbes', 'direccion' => 'Mz. 0u Lt. 00a Aa.hh. Pampa Grande, Tumbes', 'referencia' => 'Frente a la Av. Universitaria, Y Al Frente A La iglesia Mormones Y Al Lado De Un Lavadero De Autos', 'tipo' => 'Pequeña'],
            ['nombre' => 'Corrales', 'ciudad' => 'Corrales', 'departamento' => 'Tumbes', 'direccion' => 'Av. Huáscar Nº 311 Int. 01 Centro, Corrales - Tumbes', 'referencia' => 'A Espaldas De La Plaza De Armas', 'tipo' => 'Pequeña'],
            ['nombre' => 'La Cruz Tumbes', 'ciudad' => 'La Cruz', 'departamento' => 'Tumbes', 'direccion' => 'Jr. Piura 105 Caleta La Cruz, La Cruz - Tumbes', 'referencia' => 'Frente a ctr. panamericana Norte Y Al Frente De Motorepuestos Y Multiservicios Lujan', 'tipo' => 'Pequeña'],
            ['nombre' => 'Zorritos', 'ciudad' => 'Zorritos', 'departamento' => 'Tumbes', 'direccion' => 'Av. 28 De Julio n° 205 Mz. 14 Lt. 04 Los Pinos Tumbes, contralmiraante Villar - Zorritos - Tumbes', 'referencia' => '', 'tipo' => 'Mediana'],
            ['nombre' => 'Zarumilla', 'ciudad' => 'Zarumilla', 'departamento' => 'Tumbes', 'direccion' => 'Jiron Independencia 309 Zarumilla', 'referencia' => 'Atrás De La Plaza De Armas Y Frente Al Dorado Pasando 5 Casas', 'tipo' => 'Pequeña'],
            ['nombre' => 'Aguas Verdes', 'ciudad' => 'Aguas Verdes', 'departamento' => 'Tumbes', 'direccion' => 'Av Tumbes S/n Lote 09 Mz 17 , A.h Tomas Arizola Olaya , Sector Ii', 'referencia' => 'A Una Cuadra Del Parque Tomas Arizola', 'tipo' => 'Mediana'],

            // ========== UCAYALI ==========
            ['nombre' => 'Calleria Jr Jose Galvez', 'ciudad' => 'Callería', 'departamento' => 'Ucayali', 'direccion' => 'Jr. Jose Galvez 147 Calleria - Coronel Portillo - Ucayali', 'referencia' => 'A Media Cuadra De La Av. Centenario', 'tipo' => 'Mediana'],
            ['nombre' => 'Calleria Av Saenz Peña', 'ciudad' => 'Callería', 'departamento' => 'Ucayali', 'direccion' => 'Av. Saenz Peña 229, Calleria - Coronel Portillo - Ucayali', 'referencia' => 'A Dos Cuadras Del Ovalo De Federico Basadre Y Saenz Peña', 'tipo' => 'Pequeña'],
            ['nombre' => 'Pucallpa Co Federico Basadre', 'ciudad' => 'Pucallpa', 'departamento' => 'Ucayali', 'direccion' => 'Carretera Federico Basadre Km 6.800 Yarinacocha - Coronel Portillo - Ucayali', 'referencia' => 'Entrada Del Asentamiento Humano Alan Sisley/al Costado De La Empresa Jvj Service Oriente Sac', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Yarinacocha Centro', 'ciudad' => 'Yarinacocha', 'departamento' => 'Ucayali', 'direccion' => 'Jr. Tupac Amaru, Mz. 50, Lt. 07', 'referencia' => 'A Espalda De Maestranza De Yarinacocha', 'tipo' => 'Pequeña'],
            ['nombre' => 'Yarinacocha Av Universitaria', 'ciudad' => 'Yarinacocha', 'departamento' => 'Ucayali', 'direccion' => 'Av. Universitaria Mza A Lote 6, Yarinacocha - Coronel Portillo - Ucayali', 'referencia' => 'A Media Cdra. Del Local Rokalpa', 'tipo' => 'Pequeña'],
            ['nombre' => 'Manantay Av Aguaytia', 'ciudad' => 'Manantay', 'departamento' => 'Ucayali', 'direccion' => 'Av. Aguaytia Mz., 26 Lt. 20 manantay - Coronel Portillo - Ucayali', 'referencia' => 'A Media Cdra. Del Nuevo Mercado De San Fernando', 'tipo' => 'Pequeña'],
            ['nombre' => 'Manantay Av Tupac Amaru', 'ciudad' => 'Manantay', 'departamento' => 'Ucayali', 'direccion' => 'Av. Tupac Amaru 2315 manantay - Coronel Portillo - Ucayali', 'referencia' => 'A Media Cdra. De La Polleria Emanuel', 'tipo' => 'Mediana'],
            ['nombre' => 'Aguaytía', 'ciudad' => 'Aguaytía', 'departamento' => 'Ucayali', 'direccion' => 'U. Vecinal Barrio Unido Mz. 1 Lt. 2, Padre Abad - Ucayali', 'referencia' => 'Al Costado Del Terminal Terrestre De Aguaytia', 'tipo' => 'Grande / Co'],

            // ========== LIMA ==========
            // NOTA: Se realizan envíos a todos los distritos de Lima Metropolitana
            // A continuación se listan las agencias en las provincias de Lima (fuera de Lima Metropolitana)

            // ========== PROVINCIAS DE LIMA ==========
            ['nombre' => 'Barranca', 'ciudad' => 'Barranca', 'departamento' => 'Lima', 'direccion' => 'Urb. Las Vegas - Mz. C, Lt. 22 - Barranca', 'referencia' => 'A Espaldas Del Fe Y Alegría N°35 En La Urbanización Techo Propio', 'tipo' => 'Mediana'],
            ['nombre' => 'Paramonga', 'ciudad' => 'Paramonga', 'departamento' => 'Lima', 'direccion' => 'Av. Central N° 305 Mz. N1 Lt. 17', 'referencia' => 'Urb. Miguel Grau', 'tipo' => 'Mediana'],
            ['nombre' => 'Supe', 'ciudad' => 'Supe', 'departamento' => 'Lima', 'direccion' => 'Av. Francisco Vidal 1120, Supe - Barranca - Lima', 'referencia' => 'Al Costado De Lubricentro Ciriaco Y Media Cdra. De La Cruz Misionera', 'tipo' => 'Mediana'],
            ['nombre' => 'Cañete San Vicente', 'ciudad' => 'Cañete', 'departamento' => 'Lima', 'direccion' => 'Aa.hh. Víctor Andrés Belaunde Mz. B Lt. 12, San Vicente De Cañete - Cañete - Lima', 'referencia' => '', 'tipo' => 'Pequeña'],
            ['nombre' => 'Cañete Jr. Santa Rita', 'ciudad' => 'Cañete', 'departamento' => 'Lima', 'direccion' => 'Jr. Santa Rita 399', 'referencia' => 'Cruce Con Av. Libertadores', 'tipo' => 'Pequeña'],
            ['nombre' => 'Cañete Imperial', 'ciudad' => 'Cañete', 'departamento' => 'Lima', 'direccion' => 'Jr. Augusto B. Leguía N.º 457, Mz E, Centro Poblado Imperial, Imperial - Cañete - Lima', 'referencia' => 'Cevichería Brisas Del mar', 'tipo' => 'Pequeña'],
            ['nombre' => 'Chilca', 'ciudad' => 'Chilca', 'departamento' => 'Lima', 'direccion' => 'Av Nicolás De Pierola 462, Una Cuadra Antes De La Municipalidad', 'referencia' => '', 'tipo' => 'Mediana'],
            ['nombre' => 'Mala', 'ciudad' => 'Mala', 'departamento' => 'Lima', 'direccion' => 'Av. Marchand # 250, Distrito De Mala', 'referencia' => 'A Unas Casas Frente A La Distribuidora Primax Gas', 'tipo' => 'Mediana'],
            ['nombre' => 'Nuevo Imperial Co', 'ciudad' => 'Nuevo Imperial', 'departamento' => 'Lima', 'direccion' => 'Fundo Santa Adela, Mz. A, Lotes 8 Y 9 – Carretera Cañete A Yauyos Nuevo Imperial - Cañete - Lima', 'referencia' => 'Al Costado Del Restaurant la Ruta Brava', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Huaral', 'ciudad' => 'Huaral', 'departamento' => 'Lima', 'direccion' => 'Av. Jorge Chavez 647', 'referencia' => 'Entre La Av. Grau Y Bolognesi (cerca Al Paradero Moto Naturales)', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Chancay', 'ciudad' => 'Chancay', 'departamento' => 'Lima', 'direccion' => 'Prolongación San Martín N°403 Chancay', 'referencia' => 'A Una Cdra. De La Av. Panamericana Norte', 'tipo' => 'Mediana'],
            ['nombre' => 'Jicamarca', 'ciudad' => 'Jicamarca', 'departamento' => 'Lima', 'direccion' => 'Av. Sinchi Roca Mz. P Lt. 16a P Lote 16a, Aahh Las Praderas De Jicamarca – Sector El Cercado – Anexo 22 Jicamarca – Huarochiri', 'referencia' => 'Cerca Al Arco Porton De Jicamarca', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Huacho Co Prolongación Salaverry', 'ciudad' => 'Huacho', 'departamento' => 'Lima', 'direccion' => 'Prolongación Salaverry N° 764 Huacho', 'referencia' => 'Cruce Con La Av La Paz', 'tipo' => 'Grande / Co'],
            ['nombre' => 'Huacho Av Indacochea', 'ciudad' => 'Huacho', 'departamento' => 'Lima', 'direccion' => 'Av. Mercedes Indacochea 1276 Huacho - Huaura - Lima', 'referencia' => 'Intersección Con Pedro Ruiz Gallo, A 2 Cdras. De La Universidad Nacional José Faustino Sánchez Carrión', 'tipo' => 'Micro'],
            ['nombre' => 'Huaura', 'ciudad' => 'Huaura', 'departamento' => 'Lima', 'direccion' => 'Av. Las Malvinas Mz. C Lote 16 Urb. El Rosario Sur Huaura', 'referencia' => 'A Espaldas De La Plaza De Armas, A 1 Cdra. De La Calle Los Alamos', 'tipo' => 'Micro'],
            ['nombre' => 'Sayan', 'ciudad' => 'Sayán', 'departamento' => 'Lima', 'direccion' => 'Calle Naranjo N° 211.sayan - Huaura - Lima', 'referencia' => 'A Media Cdra. De La Plaza De Armas Y De La Municipalidad', 'tipo' => 'Pequeña'],

            // NOTA: Juliaca está OMITIDO completamente como se solicitó
        ];

        foreach ($agencias as $agencia) {
            AgenciaEnvio::create([
                'nombre' => $agencia['nombre'],
                'ciudad' => $agencia['ciudad'],
                'departamento' => $agencia['departamento'],
                'direccion' => $agencia['direccion'],
                'referencia' => $agencia['referencia'] ?? null,
                'tipo' => $agencia['tipo'] ?? null,
                'telefono' => null,
                'horarios' => 'Lunes a sábado de 8:00 A.m A 8:00 p.m',
                'transportista' => 'Shalom',
                'activo' => true
            ]);
        }
    }
}
